NomicFoundation/slang

- code-analysis/crates/codegen/parser/src/chumsky/boilerplate.rs
- code-analysis/crates/codegen/parser/src/chumsky/code_generator.rs
- code-analysis/crates/codegen/parser/src/chumsky/rust_lib_boilerplate.rs
- code-analysis/crates/codegen/parser/src/chumsky/rust_lib_code_generator.rs
- code-analysis/crates/codegen/parser/src/chumsky/typescript_lib_boilerplate.rs
- code-analysis/crates/codegen/parser/src/chumsky/typescript_lib_code_generator.rs
- code-analysis/crates/solidity/outputs/rust/lib/src/generated/cst.rs
- code-analysis/crates/solidity/outputs/rust/lib/src/generated/language.rs
- code-analysis/crates/solidity/outputs/rust/lib/src/generated/parse.rs
- code-analysis/crates/solidity/outputs/typescript/lib/__test__/index.spec.ts
- code-analysis/crates/solidity/outputs/typescript/lib/index.d.ts
- code-analysis/crates/solidity/outputs/typescript/lib/src/generated/cst.rs
- code-analysis/crates/solidity/outputs/typescript/lib/src/generated/language.rs
- code-analysis/crates/solidity/outputs/typescript/lib/src/generated/lex.rs
- code-analysis/crates/solidity/outputs/typescript/lib/src/generated/parse.rs
- code-analysis/crates/solidity/test_data/cst_output/contract_definition/empty_contract/generated/0.4.10.yml
- code-analysis/crates/solidity/test_data/cst_output/exponentiation_expression/operator_associativity/generated/0.4.10.yml
- code-analysis/crates/solidity/test_data/cst_output/exponentiation_expression/operator_associativity/generated/0.6.0.yml
Precursor to including errors in cst
> Include lex nodes in cst

- code-analysis/crates/solidity/samples/console.sol
Copied from https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/console.sol
> add console.log sample as a stress test case

- crates/codegen/parser/src/chumsky/boilerplate.rs
- crates/codegen/parser/src/chumsky/to_parser_code.rs
- crates/codegen/parser/src/chumsky/typescript_lib_boilerplate.rs
- crates/solidity/outputs/rust/lib/src/generated/cst.rs
- crates/solidity/outputs/rust/lib/src/generated/lex.rs
- crates/solidity/outputs/rust/lib/src/generated/parse.rs
- crates/solidity/outputs/typescript/lib/src/generated/cst.rs
- crates/solidity/outputs/typescript/lib/src/generated/lex.rs
- crates/solidity/outputs/typescript/lib/src/generated/parse.rs
> hide lex_node from the public API

- .devcontainer/devcontainer.json
- .vscode/settings.json
- crates/codegen/schema/src/validation/rules/empty_productions.rs
- scripts/_common.sh
- scripts/cargo/_common.sh
It should be checking nested expressions of sequences
> fix empty_productions schema validation

- .github/workflows/deploy.yml
> fix github pages deployment script

- .cspell.json
- README.md
- documentation/public/NAV.md
- documentation/public/index.md
- documentation/public/internals/NAV.md
- documentation/public/internals/development/index.md
> create dedicated development section instead of README

- scripts/_common.sh
- scripts/_utils.sh
- scripts/lint/all.sh
- scripts/lint/linters/cargofmt.sh
- scripts/lint/linters/cspell.sh
- scripts/lint/linters/markdown-link-check.sh
- scripts/lint/linters/markdownlint.sh
- scripts/lint/linters/prettier.sh
- scripts/lint/linters/shellcheck.sh
- scripts/lint/linters/yamllint.sh
- scripts/setup/all.sh
- scripts/setup/cargo.sh
- scripts/setup/workspace.sh
makes it much easier to debug failures in CI
> refactor and group infra logs

- Cargo.lock
- Cargo.toml
- crates/solidity/outputs/rust/slang_solidity/Cargo.toml
- crates/solidity/outputs/rust/slang_solidity/src/lib.rs
- crates/solidity/outputs/rust/slang_solidity/src/main.rs
Update the public CLI, with the correct metadata, help messages, and flags.
> prepare slang_solidity CLI

- crates/solidity/outputs/typescript/lib/index.js
- documentation/public/assets/scripts/grammar-navigation.js
- package-lock.json
- package.json
- scripts/lint/all.sh
- scripts/lint/linters/tsc.sh
- scripts/lint/package.json
- tsconfig.json
this also type checks/lints the generated typescript parser package
> add tsc linter for ts/js files

- SECURITY.md
cc @fzeoli @alcuadrado for review. Please let me know if there is another email/link that can be used instead.
> create SECURITY.md policy

- crates/solidity/testing/snapshots/cst_output/StringExpression/unicode_multiple/generated/0.4.11.yml
- crates/solidity/testing/snapshots/cst_output/StringExpression/unicode_single/generated/0.4.11.yml
- crates/solidity/testing/utils/src/cst_snapshots/mod.rs
- crates/solidity/testing/utils/src/cst_snapshots/test_nodes.rs
- crates/solidity/testing/utils/src/node_extensions/mod.rs
> use byte indexes in test snapshots

- crates/solidity/testing/smoke/src/main.rs
- crates/solidity/testing/utils/src/lib.rs
- crates/solidity/testing/utils/src/version_pragmas/mod.rs
- crates/solidity/testing/utils/src/version_pragmas/tests.rs
skipping invalid files, now smoke tests are running smoothly with no errors.
closes #341
> fix smoke tests parsing pragmas

- package-lock.json
- scripts/changelog/update-lock-files.sh
script was failing because git user was not configured
> fix script to update lock files after release

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/_jobs_check.yml
> use prebuilt docker image for devcontainer

- crates/solidity/outputs/npm/package/package.json
- crates/solidity/outputs/npm/tests/package.json
- package-lock.json
- scripts/changelog/package.json
- scripts/lint/package.json
Attempt to fix https://github.com/NomicFoundation/slang/security/dependabot/17
> update npm dependencies

- crates/solidity/inputs/language/definition/01-file-structure/03-pragmas/productions.yml
- crates/solidity/outputs/cargo/crate/src/generated/parsers.rs
- crates/solidity/outputs/cargo/tests/src/cst_output/generated/PragmaDirective.rs
- crates/solidity/outputs/npm/crate/src/generated/parsers.rs
- crates/solidity/outputs/spec/generated/ebnf/01-file-structure/03-pragmas/experimental-pragma/unversioned.md
- crates/solidity/testing/snapshots/cst_output/PragmaDirective/experimental_string/generated/0.4.11.yml
- crates/solidity/testing/snapshots/cst_output/PragmaDirective/experimental_string/input.sol
Fixes problems parsing sanctuary.
> Allow ascii string literal as experimental pragma value

- crates/solidity/testing/smoke/src/main.rs
Currently it tries to test all supported minor versions. This changes the algorithm to test all versions that have breaking changes in them (minor or patch), since Solidity has a few patch breaks as well.
> update smoke tests version ranges

- crates/solidity/inputs/language/definition/04-statements/01-blocks/notes.md
Follow up on https://github.com/NomicFoundation/slang/pull/532#discussion_r1259700265
> update documentation for unchecked blocks

- crates/codegen/parser/generator/src/parser_definition.rs
- crates/codegen/parser/generator/src/precedence_parser_definition.rs
- crates/codegen/parser/runtime/src/support/choice_helper.rs
- crates/codegen/parser/runtime/src/support/optional_helper.rs
- crates/codegen/parser/runtime/src/support/parser_function.rs
- crates/codegen/parser/runtime/src/support/parser_result.rs
- crates/codegen/parser/runtime/src/support/repetition_helper.rs
- crates/codegen/parser/runtime/src/support/sequence_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/language.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/choice_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/optional_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/parser_function.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/parser_result.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/repetition_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/sequence_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
- crates/solidity/outputs/npm/crate/src/generated/support/choice_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/support/optional_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/support/parser_function.rs
- crates/solidity/outputs/npm/crate/src/generated/support/parser_result.rs
- crates/solidity/outputs/npm/crate/src/generated/support/repetition_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/support/sequence_helper.rs
Most importantly, this documents and tries to simplify the parser helpers and improves legibility of the generated parse functions. Done as part of the #567
> Polish parser helpers

- .github/workflows/_jobs_ci.yml
- .github/workflows/_jobs_github_pages.yml
- .github/workflows/_jobs_publish.yml
- scripts/_common.sh
add the rest of cache folders to CI cache
> update CI cache

- package-lock.json
https://github.com/NomicFoundation/slang/security/dependabot/26
> update package-lock.json to fix security/dependabot/26

- crates/codegen/parser/runtime/src/support/choice_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/choice_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/support/choice_helper.rs
remove the duplicate word 'the'.
> remove the duplicate word

- .changeset/hip-mails-wonder.md
- crates/codegen/parser/runtime/src/cursor.rs
- crates/codegen/parser/runtime/src/support/choice_helper.rs
- crates/codegen/parser/runtime/src/support/parser_function.rs
- crates/codegen/parser/runtime/src/support/parser_result.rs
- crates/codegen/parser/runtime/src/visitor.rs
- crates/solidity/outputs/cargo/crate/src/generated/cursor.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/choice_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/parser_function.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/parser_result.rs
- crates/solidity/outputs/cargo/crate/src/generated/visitor.rs
- crates/solidity/outputs/cargo/tests/src/doc_examples/cursor_api.rs
- crates/solidity/outputs/cargo/tests/src/doc_examples/visitor_api.rs
- crates/solidity/outputs/npm/crate/src/generated/cursor.rs
- crates/solidity/outputs/npm/crate/src/generated/support/choice_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/support/parser_function.rs
- crates/solidity/outputs/npm/crate/src/generated/support/parser_result.rs
- crates/solidity/outputs/npm/crate/src/generated/visitor.rs
- crates/solidity/testing/utils/src/cst_snapshots/test_nodes.rs
- documentation/public/user-guide/cargo-crate/index.md
Closes #609
Still needs tweaking to adapt to the current Cursor's behavior and needs more documentation/tests for the Visitor trait.
> Implement Iterator for Cursor 

- documentation/public/internals/design-docs/language-definition-v2/index.md
- documentation/public/user-guide/rust-crate/how-to-parse-a-file/index.md
> fix typos in documentation

- Cargo.lock
- Cargo.toml
- crates/codegen/parser/runtime/src/napi/napi_cst.rs
- crates/codegen/parser/runtime/src/templates/language.rs.jinja2
- crates/solidity/outputs/cargo/crate/src/generated/language.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/napi_cst.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/napi_cst.rs
more details: https://github.com/napi-rs/napi-rs/issues/1852
> upgrade napi version

- crates/codegen/parser/runtime/src/napi/mod.rs
- crates/codegen/parser/runtime/src/napi/napi_cursor.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/mod.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/napi_cursor.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/mod.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/napi_cursor.rs
- crates/solidity/outputs/npm/package/src/generated/index.d.ts
- crates/solidity/outputs/npm/package/src/kinds/index.ts
- crates/solidity/outputs/npm/tests/src/tests/cst-cursor.ts
Part of #710 #713
Forgot to expose the relevant function in NAPI.
> Expose the Cursor.nodeName on the NAPI side

- .changeset/silver-buttons-relax.md
- crates/codegen/parser/runtime/src/napi/napi_cst.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/napi_cst.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/napi_cst.rs
- crates/solidity/outputs/npm/package/src/generated/index.d.ts
- crates/solidity/outputs/npm/tests/src/tests/cst-output.ts
> add `RuleNode.unparse()` to the TypeScript API

- .github/workflows/_jobs_github_pages.yml
- .github/workflows/_jobs_publish.yml
- .github/workflows/deploy.yml
Broken by an additional validation rule that seems to be added recently: https://github.com/NomicFoundation/slang/actions/runs/7774470067
> fix github pages deployment workflow

- .changeset/afraid-waves-move.md
- crates/codegen/parser/generator/src/trie.rs
- crates/solidity/inputs/language/src/definition.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/language.rs
- crates/solidity/outputs/cargo/tests/src/cst_output/generated/VariableDeclarationStatement.rs
- crates/solidity/outputs/spec/generated/grammar.ebnf
- crates/solidity/outputs/spec/generated/public/01-file-structure/03-pragma-directives.md
- crates/solidity/testing/snapshots/cst_output/VariableDeclarationStatement/keyword_abicoder/generated/0.4.11-success.yml
- crates/solidity/testing/snapshots/cst_output/VariableDeclarationStatement/keyword_abicoder/input.sol
- crates/solidity/testing/snapshots/cst_output/VariableDeclarationStatement/keyword_experimental/generated/0.4.11-success.yml
- crates/solidity/testing/snapshots/cst_output/VariableDeclarationStatement/keyword_experimental/input.sol
- crates/solidity/testing/snapshots/cst_output/VariableDeclarationStatement/keyword_solidity/generated/0.4.11-success.yml
- crates/solidity/testing/snapshots/cst_output/VariableDeclarationStatement/keyword_solidity/input.sol
More context: https://github.com/NomicFoundation/slang/pull/661#discussion_r1399821140
> unreserve pragma keywords in all versions

- .changeset/lemon-knives-fry.md
- crates/codegen/parser/generator/src/ast_model.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/napi_interface/ast_selectors.rs
- crates/solidity/outputs/npm/package/src/ast/generated/ast_types.ts
- crates/testlang/inputs/language/src/definition.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/kinds.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/language.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/napi_interface/ast_selectors.rs
- crates/testlang/outputs/cargo/slang_testlang/src/lib.rs
- crates/testlang/outputs/npm/package/src/ast/generated/ast_types.ts
- crates/testlang/outputs/npm/package/src/generated/index.d.ts
- crates/testlang/outputs/npm/tests/src/tests/ast.ts
Added tests to the existing suite.
> fix selection order of prefix/postfix AST fields

- crates/codegen/grammar/src/constructor.rs
- crates/codegen/parser/generator/src/ast_model.rs
- crates/codegen/parser/runtime/src/cursor.rs
- crates/codegen/parser/runtime/src/query/parser.rs
- crates/codegen/parser/runtime/src/templates/language.rs.jinja2
- crates/solidity/outputs/cargo/slang_solidity/src/generated/cursor.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/language.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/query/parser.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/cursor.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/query/parser.rs
just a round of clean up for any remaining/undocumented work.
> attach issues to remaining TODO comments in code

- crates/solidity/testing/sanctuary/src/main.rs
- crates/solidity/testing/sanctuary/src/tests.rs
> Skip contracts from Sanctuary that rely on exotic parser bugs

- crates/solidity/testing/sanctuary/src/tests.rs
See https://github.com/NomicFoundation/slang/pull/921#issuecomment-2046952672
> Add another contract to the sanctuary blocklist

- crates/solidity/outputs/npm/package/package.json
- crates/solidity/outputs/npm/package/platforms/darwin-arm64/package.json
- crates/solidity/outputs/npm/package/platforms/darwin-x64/package.json
- crates/solidity/outputs/npm/package/platforms/linux-arm64-gnu/package.json
- crates/solidity/outputs/npm/package/platforms/linux-arm64-musl/package.json
- crates/solidity/outputs/npm/package/platforms/linux-x64-gnu/package.json
- crates/solidity/outputs/npm/package/platforms/linux-x64-musl/package.json
- crates/solidity/outputs/npm/package/platforms/win32-arm64-msvc/package.json
- crates/solidity/outputs/npm/package/platforms/win32-ia32-msvc/package.json
- crates/solidity/outputs/npm/package/platforms/win32-x64-msvc/package.json
- package-lock.json
- package.json
> switch to NAPI required deps

- .github/workflows/review-requested-slack-notification.yml
- .github/workflows/review-submitted-slack-notification.yml
This PR adds the workflows that notifies about PR reviews via Slack
> Add workflows for Slack PR review notifications

- .cargo/config.toml
- .devcontainer/Dockerfile
- Cargo.lock
- Cargo.toml
- crates/infra/cli/src/commands/mod.rs
- crates/infra/cli/src/commands/perf/mod.rs
- crates/infra/cli/src/commands/setup/mod.rs
- crates/infra/cli/src/commands/setup/shell_completions/mod.rs
- crates/infra/utils/Cargo.toml
- crates/infra/utils/src/cargo/manifest.rs
- crates/infra/utils/src/cargo/workspace.rs
- crates/solidity/testing/perf/Cargo.toml
- crates/solidity/testing/perf/benches/iai/dataset.rs
- crates/solidity/testing/perf/benches/iai/main.rs
- crates/solidity/testing/perf/benches/iai/sources/ERC20.sol
- crates/solidity/testing/perf/benches/iai/sources/ERC721.sol
- crates/solidity/testing/perf/benches/iai/sources/EnumerableMap.sol
- crates/solidity/testing/perf/benches/iai/sources/Governor.sol
- crates/solidity/testing/perf/benches/iai/sources/SafeCast.sol
adds a new `infra perf benchmark` command that runs and reports results to <bencher.dev>.
> add perf testing

- .github/workflows/publish.yml
- Pipfile
- Pipfile.lock
- crates/infra/cli/src/commands/check/mod.rs
- crates/infra/cli/src/commands/lint/mod.rs
- crates/infra/cli/src/commands/mod.rs
- crates/infra/cli/src/commands/publish/cargo/mod.rs
- crates/infra/cli/src/commands/publish/changesets/mod.rs
- crates/infra/cli/src/commands/publish/github_release/mod.rs
- crates/infra/cli/src/commands/publish/mkdocs/mod.rs
- crates/infra/cli/src/commands/publish/mod.rs
- crates/infra/cli/src/commands/publish/npm/mod.rs
- crates/infra/cli/src/commands/setup/git/mod.rs
- crates/infra/cli/src/commands/setup/mod.rs
- crates/infra/cli/src/commands/setup/pipenv/mod.rs
- crates/infra/cli/src/toolchains/mkdocs/mod.rs
- crates/infra/cli/src/toolchains/mod.rs
- crates/infra/cli/src/toolchains/pipenv/mod.rs
- crates/infra/cli/src/utils.rs
- crates/infra/utils/src/git/mod.rs
- documentation/mkdocs.yml
- documentation/overrides/main.html
> add versioning to mkdocs

- crates/solidity/testing/perf/benches/iai/dataset.rs
after query syntax update in #1030
> update perf tests

- .github/workflows/sanctuary.yml
Was doing a manual run, and noticed the typo in the CI workflow. Fixed here.
> fix sanctuary CI command

- Cargo.lock
- Cargo.toml
- crates/infra/cli/src/commands/publish/cargo/mod.rs
- crates/infra/cli/src/commands/setup/cargo/mod.rs
- crates/infra/utils/Cargo.toml
- crates/infra/utils/src/cargo/mod.rs
- crates/infra/utils/src/cargo/public_api.rs
- crates/metaslang/bindings/generated/public_api.txt
- crates/metaslang/cst/generated/public_api.txt
- crates/metaslang/graph_builder/generated/public_api.txt
- crates/solidity/outputs/cargo/slang_solidity/generated/public_api.txt
This will make sure any additions/removals impacting users is accounted for.
> generate snapshots of the Rust public API

- crates/solidity/inputs/language/bindings/rules.msgb
- crates/solidity/outputs/cargo/slang_solidity/src/generated/bindings/generated/binding_rules.rs
- crates/solidity/outputs/cargo/tests/src/bindings_assertions/generated/mod.rs
- crates/solidity/outputs/cargo/tests/src/bindings_assertions/generated/yul.rs
- crates/solidity/outputs/cargo/tests/src/bindings_output/generated/mod.rs
- crates/solidity/outputs/cargo/tests/src/bindings_output/generated/yul.rs
- crates/solidity/testing/snapshots/bindings_assertions/yul/blocks.sol
- crates/solidity/testing/snapshots/bindings_assertions/yul/fun_scopes.sol
- crates/solidity/testing/snapshots/bindings_assertions/yul/functions.sol
- crates/solidity/testing/snapshots/bindings_assertions/yul/if_stmt.sol
- crates/solidity/testing/snapshots/bindings_assertions/yul/labels.sol
- crates/solidity/testing/snapshots/bindings_assertions/yul/stack_assign.sol
- crates/solidity/testing/snapshots/bindings_assertions/yul/variables.sol
- crates/solidity/testing/snapshots/bindings_output/yul/conditionals/generated/0.4.11-success.txt
- crates/solidity/testing/snapshots/bindings_output/yul/conditionals/input.sol
- crates/solidity/testing/snapshots/bindings_output/yul/functions/generated/0.4.11-success.txt
- crates/solidity/testing/snapshots/bindings_output/yul/functions/input.sol
- crates/solidity/testing/snapshots/bindings_output/yul/loops/generated/0.4.11-success.txt
- crates/solidity/testing/snapshots/bindings_output/yul/loops/input.sol
- crates/solidity/testing/snapshots/bindings_output/yul/variables/generated/0.4.11-success.txt
- crates/solidity/testing/snapshots/bindings_output/yul/variables/input.sol
Adds binding rules to support inline Yul assembly
> Binding rules for inline assembly

- Cargo.toml
- crates/infra/cli/src/commands/perf/benchmark/mod.rs
- crates/infra/utils/src/commands/mod.rs
- fix versioning issue caused by https://github.com/dependabot/dependabot-core/issues/10542
- add `--dry-run` for local testing
> fix perf CI build

- crates/infra/utils/src/cargo/manifest.rs
- crates/infra/utils/src/cargo/public_api.rs
- crates/infra/utils/src/cargo/workspace.rs
- crates/metaslang/bindings/generated/public_api.txt
- crates/metaslang/cst/generated/public_api.txt
- crates/metaslang/graph_builder/generated/public_api.txt
- crates/solidity/outputs/cargo/slang_solidity/generated/public_api.txt
- omit auto trait impls.
- omit blanket impls.
> simplify public API snapshots

- .vscode/settings.json
- Cargo.toml
- bin/hermit.hcl
- crates/codegen/runtime/cargo/crate/src/runtime/parser/parser_support/sequence_helper.rs
- crates/infra/cli/src/commands/lint/mod.rs
- crates/infra/utils/src/cargo/public_api.rs
- crates/metaslang/bindings/src/resolver/mod.rs
- crates/metaslang/graph_builder/src/excerpt.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser/parser_support/sequence_helper.rs
- crates/solidity/testing/perf/benches/iai/main.rs
- crates/solidity/testing/perf/benches/iai/tests/cursor.rs
- crates/solidity/testing/perf/benches/iai/tests/definitions.rs
- crates/solidity/testing/perf/benches/iai/tests/init_bindings.rs
- crates/solidity/testing/perf/benches/iai/tests/query.rs
- crates/solidity/testing/perf/benches/iai/tests/references.rs
- crates/testlang/outputs/cargo/crate/src/generated/parser/parser_support/sequence_helper.rs
It has been [failing in CI](https://github.com/NomicFoundation/slang/actions/runs/11597323701/job/32290519984) for a few days.
This fixes it by upgrading `RUST_STABLE_VERSION` and `RUST_NIGHTLY_VERSION` to latest.
> fix benchmarking in CI

- CODEOWNERS
Fixes #1136
Looks like later entries override earlier ones, not add to them.
> Update root CODEOWNERS

- crates/codegen/runtime/cargo/wasm/src/runtime/interface/cst.wit.jinja2
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/generated/cst.wit
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/generated/parser.wit
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/parser.wit.jinja2
- crates/solidity/outputs/cargo/wasm/src/generated/interface/generated/cst.wit
- crates/solidity/outputs/cargo/wasm/src/generated/interface/generated/parser.wit
- crates/testlang/outputs/cargo/wasm/src/generated/interface/generated/cst.wit
- crates/testlang/outputs/cargo/wasm/src/generated/interface/generated/parser.wit
Not comprehensive. Some things like specific node kinds and AST types are not documented yet.
> add doc comments to some of the WIT APIs

- crates/metaslang/bindings/Cargo.toml
- crates/metaslang/cst/Cargo.toml
- crates/metaslang/graph_builder/Cargo.toml
- crates/solidity/outputs/cargo/cli/Cargo.toml
- crates/solidity/outputs/cargo/crate/Cargo.toml
- crates/solidity/outputs/npm/package/package.json
Adding the team alias, rather than individual members.
> update packages metadata

- package-lock.json
closes https://github.com/NomicFoundation/slang/security/dependabot/60
> update npm lock files

- .devcontainer/devcontainer.json
- .vscode/extensions.json
Added one extension for GitHub pull requests and one extension for GitHub repositories.
> Added two extentions for GitHub.

- package-lock.json
Closes https://github.com/NomicFoundation/slang/security/dependabot/78
> run `npm audit fix`

- .gitmodules
- crates/infra/cli/package.json
- crates/infra/cli/src/commands/setup/mod.rs
- crates/infra/cli/src/commands/setup/npm/mod.rs
- crates/infra/cli/src/toolchains/wasm/mod.rs
- package-lock.json
Waiting for https://github.com/NomicFoundation/jco/pull/18
> use `jco` from npm

- .github/workflows/benchmark_cargo.yml
- .github/workflows/benchmark_npm.yml
- Cargo.lock
- Cargo.toml
- crates/infra/cli/src/commands/perf/cargo/mod.rs
- crates/infra/cli/src/commands/perf/npm/mod.rs
- crates/infra/cli/src/toolchains/bencher/mod.rs
The merge of the `Cargo.toml` file from #1287 went bananas 🤷 
Another fix (not unexpected, this was my inexperience with GH Actions) make the perf commands fail when trigger by push.
> Fixing merge issue
