- code-analysis/Cargo.lock
- code-analysis/crates/codegen/utils/Cargo.toml
- code-analysis/crates/codegen/utils/src/files.rs
Produces a visual/colored diffs for test failures, instead of just the file path.
> use similar_asserts for codegen assertions

- bin/hermit.hcl
- code-analysis/Cargo.lock
- code-analysis/crates/solidity/outputs/rust/cli/Cargo.toml
- code-analysis/crates/solidity/outputs/rust/cli/src/main.rs
- code-analysis/scripts/bin/README.md
- code-analysis/scripts/bin/_slang_cargo_bin_runner.sh
- code-analysis/scripts/bin/solidity_rust_cli
Added a `code-analysis/scripts/bin` folder that contains scripts/shorthands for rust binaries we add to the Cargo workspace.
These scripts read and reuse the same configs used by other build/test scripts.
For now, it only has a single script: `solidity_rust_cli`.
And since I added this folder to the hermit environment `$PATH`, it can be directly invoked from any folder:
```bash
solidity_rust_cli --version 0.8.0 ./code-analysis/crates/solidity/samples/Bee_token.sol' --json -
```
Whenever we add new binaries (internal or external), we should add a new script to this folder:
```bash
cd "$REPO_ROOT/code-analysis/scripts/bin"
ln -s _slang_cargo_bin_runner.sh THE_NEW_BINARY_NAME
```
I also added a bunch of tiny improvements for issues I found while using this single binary:
- Fixed a bug where …
> improvements to cargo run binaries

- code-analysis/Cargo.toml
Found it really hard to debug failures/errors without it enabled.
I ran a few tests by changing `boilerplate.rs` (to regenerate the parser code) and running `time cargo build`, and difference was ignorable.
Before:
- cargo build  24.38s user 4.05s system 196% cpu 14.494 total
- cargo build  24.42s user 3.57s system 195% cpu 14.304 total
- cargo build  24.86s user 3.63s system 190% cpu 14.965 total
After:
- cargo build  25.93s user 3.87s system 188% cpu 15.799 total
- cargo build  25.51s user 3.76s system 181% cpu 16.090 total
- cargo build  25.36s user 3.67s system 190% cpu 15.232 total
> turn on debugging information

- crates/codegen/utils/src/commands.rs
- crates/codegen/utils/src/internal/files.rs
- crates/codegen/utils/src/internal/formatting.rs
- fixed an issue where failures were propagated without context (the invoked command)
- let build scripts run under hermit without invoking `git` first.
> improvements to commands util

- crates/codegen/utils/src/context.rs
Not only they are unnecessary, but they pollute the output of running tests and other CLI invocations.
> skip printing cargo markers during tests

- crates/codegen/parser/src/chumsky/boilerplate.rs
- crates/codegen/parser/src/chumsky/rust_lib_boilerplate.rs
- crates/codegen/parser/src/chumsky/typescript_lib_boilerplate.rs
- crates/solidity/outputs/rust/lib/src/generated/language.rs
- crates/solidity/outputs/rust/tests/src/cst_output/generated/ContractDefinition.rs
- crates/solidity/outputs/typescript/lib/src/generated/language.rs
- crates/solidity/testing/snapshots/cst_output/ContractDefinition/zero_length_input/generated/0.4.11.yml
It fails to report errors on empty strings with:
```
thread 'cst_output::generated::ContractDefinition::zero_length_input' panicked at 'index out of bounds: the len is 0 but the index is 0'.
```
This PR just returns the error message without the report in this case.
> fix ariadne error on empty strings

- .yamllint.yml
- scripts/linting/Pipfile
- scripts/linting/Pipfile.lock
- scripts/linting/linters/yamllint.sh
- scripts/linting/run.sh
Editing YAML repeatedly without clear diffrentiation between a boolean value `true` and a string value with the same contents. I also think the grammar terminals much harder to read (and grep across) without double quotes, so I'm adding `yamllint` to check for such errors, and already fixed the existing violations in a separate PR.
Please see the added `.yamllint.yml` for the list of enabled rules, and let me know if you have any feedback. I took the liberty to enable a few other ones I found helpful, but happy to be convinced otherwise: https://yamllint.readthedocs.io/en/stable/rules.html
> add yamllint for grammar files

- Cargo.lock
- crates/codegen/ebnf/src/expression.rs
- crates/codegen/parser/src/chumsky/character_filter.rs
- crates/codegen/parser/src/chumsky/combinator_node.rs
- crates/codegen/parser/src/chumsky/terminal_trie.rs
- crates/codegen/schema/Cargo.toml
- crates/codegen/schema/generated/topic.schema.json
- crates/codegen/schema/src/types/productions.rs
- crates/codegen/schema/src/validation/ast/files.rs
- crates/codegen/schema/src/validation/ast/manifest.rs
- crates/codegen/schema/src/validation/ast/productions.rs
- crates/codegen/schema/src/validation/ast/utils.rs
- crates/codegen/schema/src/validation/ast/visitors.rs
- crates/codegen/schema/src/validation/rules/empty_tokens.rs
- crates/codegen/schema/src/validation/rules/references.rs
- crates/codegen/spec/src/productions.rs
It is a remnant of the old days when we parsed EBNF grammar. `EBNF` is not really representative of what it does, since we added many non-standard variants, like `range` and `difference` and removing it will make things clearer for new comers/readers.
Also using struct enum variants, instead of separate structs, to make the callsites more readable. This matches users in `codegen_schema::validation::ast` and `codegen_parser::chumsky`.
Also refactored validation code to match. One day, I would like to automatically generate the AST from rust types via a separate `[Derive]` macro, but the current code works and is a good first step.
> rename EBNF to ExpressionParser

- scripts/_common.sh
Was producing inconsistent errors on the command line.
This sorts the files that get sent to different linters.
> sort rg output by path for deterministic linting

- .vscode/tasks.json
- crates/codegen/utils/src/errors.rs
- scripts/solidity/check-grammar.sh
Enables calling `scripts/solidity/check-grammar.sh` to get ariadne reports of any issues.
> allow solidity grammar checks to be invoked from command line

- crates/codegen/schema/src/validation/ast/productions.rs
- crates/codegen/schema/src/validation/ast/visitors.rs
- crates/codegen/schema/src/validation/mod.rs
- crates/codegen/schema/src/validation/rules/empty_productions.rs
- crates/codegen/schema/src/validation/rules/mod.rs
- crates/codegen/schema/src/validation/rules/references.rs
Making sure each token consumes at least one character.
> validate non-empty top-level expressions

- Cargo.toml
- crates/solidity/testing/smoke/src/main.rs
- crates/solidity/testing/smoke/src/reporting.rs
- crates/solidity/testing/utils/src/compatible_versions/mod.rs
- crates/solidity/testing/utils/src/compatible_versions/tests.rs
- scripts/cargo/_common.sh
- fix parsing/extracting versions from files with unicode characters
- display accurate progress/failure percent so far
- removed some defaults from `Cargo.toml`
- using `--codegen target-cpu=native` for local scripts for faster execution.
> update smoking tests

- .devcontainer/devcontainer.json
- .vscode/settings.json
- scripts/_common.sh
- scripts/cargo/_common.sh
- remove hermit files from rg linter file search, as it was including files in `$REPO_ROOT/.hermit` in linting.
- use local rust-analyzer binary: https://github.com/rust-lang/rust-analyzer/pull/13993
- showing the `unused_crate_dependencies` cargo warning locally, not just CI.
> build infra fixes

- .vscode/settings.json
- bin/hermit.hcl
- crates/codegen/utils/src/context.rs
- crates/codegen/utils/src/internal/files.rs
- scripts/_common.sh
- scripts/_utils.sh
- scripts/cargo/_common.sh
To get diagnostics, `rust-analyzer` runs `cargo check` under the hood. But when we run local check/test scripts, we run `cargo check` again, adding custom flags.
This breaks incremental builds, and forces it to check all crates again. Now local REPL takes twice as long!
This PR makes sure that both invocations will have the same exact settings and environment variables.
Note: unfortunately, we cannot put default `RUSTFLAGS` in Cargo's config files, because any environment variable usage (e.g. CI builds) overwrites it. It needs to be additive.
> unify RA and shell scripts env

- crates/solidity/inputs/schema/grammar/01-file-structure/05-trivia/productions.yml
- crates/solidity/outputs/rust/lib/src/generated/parsers.rs
- crates/solidity/outputs/rust/lib/src/generated/scanners.rs
- crates/solidity/outputs/rust/tests/src/cst_output/generated/SourceUnit.rs
- crates/solidity/outputs/spec/generated/ebnf/01-file-structure/05-trivia/end-of-line.html
- crates/solidity/outputs/spec/generated/ebnf/01-file-structure/05-trivia/trailing-trivia.html
- crates/solidity/outputs/typescript/lib/src/generated/parsers.rs
- crates/solidity/outputs/typescript/lib/src/generated/scanners.rs
- crates/solidity/testing/snapshots/cst_output/InterfaceDefinition/sample_counter/generated/0.4.11.yml
- crates/solidity/testing/snapshots/cst_output/SourceUnit/trailing_trivia/generated/0.4.11.yml
- crates/solidity/testing/snapshots/cst_output/SourceUnit/trailing_trivia/input.sol
- Using a separate tokens for each newline, to convey this information to users, instead of relying on them to reparse trivia to count lines.
- This also fixes the issue where `TrailingTrivia` scans all subsequent newlines. Now it will only scan a single newline character on the same line.
> use separate tokens for each newline

- scripts/cargo/publish.sh
typo from earlier pr:
```log
scripts/cargo/publish.sh: line 26: return: can only `return' from a function or sourced script
```
> fix cargo publish scripts

- .changeset/early-turtles-rest.md
- crates/solidity/inputs/schema/grammar/05-expressions/02-primary-expressions/productions.yml
- crates/solidity/outputs/cargo/crate/src/syntax/generated/parsers.rs
- crates/solidity/outputs/cargo/tests/src/cst_output/generated/Expression.rs
- crates/solidity/outputs/npm/crate/src/syntax/generated/parsers.rs
- crates/solidity/outputs/spec/generated/ebnf/05-expressions/02-primary-expressions/primary-expression/0.4.11.md
- crates/solidity/outputs/spec/generated/ebnf/05-expressions/02-primary-expressions/primary-expression/0.5.3.md
- crates/solidity/testing/snapshots/cst_output/Expression/unicode_string_literal/generated/0.4.11.yml
- crates/solidity/testing/snapshots/cst_output/Expression/unicode_string_literal/input.sol
sorted primary expressions to attempt sub-expressions with unique prefixes first, then literals, then identifiers at last. This prevents cases where parser recognizes an identifier at the start of `unicode""` literals.
> fix unicode string parsing

- crates/solidity/outputs/cargo/crate/Cargo.toml
This should fix the `non-standard` license field shown on https://crates.io/crates/slang_solidity
> fix published crate license field

- .cargo/config.toml
- .vscode/settings.json
- Cargo.toml
- bin/hermit.hcl
- crates/codegen/utils/src/context.rs
- scripts/_common.sh
- scripts/cargo/check.sh
- scripts/npm/napi/build.sh
Unfortunately we cannot edit `$RUSTFLAGS` env var as it breaks rust compilation incrementability. Let's move to using `build.rustflags` config variable instead.
> set rustflags from cargo toml

- Cargo.toml
- bin/hermit.hcl
Needed to use `cargo-xwin` to compile NAPI binaries on windows.
> upgrade to rust 1.65.0

- .changeset/silver-geese-clap.md
- crates/codegen/syntax_templates/src/rust/cst_visitor.rs
- crates/solidity/outputs/cargo/crate/src/generated/cst_visitor.rs
Since it is not actually stepping into anything, but it is just about to step out of the current node.
> rename `VisitorExitResponse::StepIn` to `VisitorExitResponse::Continue`

- .changeset/itchy-bulldogs-roll.md
- crates/codegen/syntax_templates/src/rust/parser_output.rs
- crates/codegen/syntax_templates/src/shared/language.rs
- crates/codegen/syntax_templates/src/typescript/parser_output.rs
- crates/solidity/outputs/cargo/crate/src/generated/language.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser_output.rs
- crates/solidity/outputs/cargo/crate/src/lib.rs
- crates/solidity/outputs/cargo/crate/src/main.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
- crates/solidity/outputs/npm/crate/src/generated/parser_output.rs
- crates/solidity/outputs/npm/package/src/generated/index.d.ts
- crates/solidity/outputs/npm/package/src/generated/index.js
- crates/solidity/outputs/npm/tests/src/index.spec.ts
- crates/solidity/testing/smoke/src/reporting.rs
- crates/solidity/testing/utils/src/cst_snapshots/mod.rs
- crates/solidity/testing/utils/src/node_extensions/tests.rs
We should have a fully typed error tree, rich with any metadata that downstream consumers might need to provide a good experience to their users.
Until that API is finalized, let's just return the `ParseError` for now.
> expose `ParseError` API

- .changeset/hot-frogs-itch.md
- crates/codegen/syntax/src/typescript_lib_code_generator.rs
- crates/codegen/syntax_templates/src/typescript/cst_types.rs
- crates/codegen/syntax_templates/src/typescript/parser_output.rs
- crates/solidity/outputs/npm/crate/src/generated/cst_types.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
- crates/solidity/outputs/npm/crate/src/generated/parser_output.rs
- crates/solidity/outputs/npm/package/src/generated/index.d.ts
- crates/solidity/outputs/npm/tests/src/index.spec.ts
Turns out that using `#[napi(ts_return_type = "number")]` only affects the return type in the generated `index.d.ts` file, but not the actual return type at runtime. Currently we are using `usize`, which maps to JavaScript's `BigInt` by default, which means our types are incorrect.
This PR uses `u32` instead which maps to JavaScript's `number` type. Also adds a few missing `getter` attributes, and adds a test to check the new types.
Follow up on #458
> use `number` and getters in npm public API

- crates/codegen/ebnf/src/precedence_parser.rs
- crates/codegen/schema/src/types/precedence_parser.rs
- crates/codegen/schema/src/validation/rules/definitions/mod.rs
- crates/codegen/schema/src/validation/visitors/receivers.rs
- crates/codegen/syntax/src/combinator_node.rs
- crates/solidity/inputs/language/definition/01-file-structure/03-pragmas/productions.yml
- crates/solidity/inputs/language/definition/03-types/01-advanced-types/productions.yml
- crates/solidity/inputs/language/definition/05-expressions/01-base-expressions/productions.yml
- crates/solidity/inputs/language/definition/06-yul/03-yul-expressions/productions.yml
- crates/solidity/inputs/language/generated/productions.schema.json
Part of tightening the grammar. This removes `PrecedenceParser.name` since it is idle/unused in codegen.
> remove `PrecedenceParser.name`

- crates/codegen/syntax/src/combinator_node.rs
- crates/codegen/syntax/src/to_parser_code.rs
Context: https://github.com/NomicFoundation/slang/issues/339#issuecomment-1458114009
add support for naming `choice` parsers, as we can have two nodes of the same kind in succession, and we need to differentiate which is which.
Closes #339
> make sure all named sub-parsers can produce rule kinds

- crates/solidity/inputs/language/src/lib.rs
- crates/solidity/outputs/cargo/crate/src/lib.rs
- crates/solidity/outputs/cargo/crate/src/main.rs
making sure to trigger codegen correctly on any changes in the language definition or codegen crates.
> fix cargo incremental builds

- Cargo.lock
- crates/codegen/syntax/src/code_generator.rs
- crates/codegen/syntax/src/rust_lib_code_generator.rs
- crates/codegen/syntax/src/to_parser_code.rs
- crates/codegen/syntax/src/typescript_lib_code_generator.rs
- crates/codegen/syntax_templates/src/rust/kinds.rs
- crates/codegen/syntax_templates/src/shared/language.rs
- crates/codegen/syntax_templates/src/typescript/kinds.rs
- crates/solidity/outputs/cargo/crate/src/generated/kinds.rs
- crates/solidity/outputs/cargo/crate/src/generated/language.rs
- crates/solidity/outputs/cargo/crate/src/generated/parsers.rs
- crates/solidity/outputs/npm/crate/Cargo.toml
- crates/solidity/outputs/npm/crate/src/generated/kinds.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
- crates/solidity/outputs/npm/crate/src/generated/parsers.rs
- move parsing tokens to a common function
- remove the need to pass token names as static strings everywhere, since we already have `strum::AsRefStr` deriver
This decreases nesting, improves readability of the parser code, and decreases the generated code by roughly 30%.
But most importantly, it unblocks #498 and #500 by making it easier to generate named or unnamed nodes at each parser root.
> refactor parser codegen

- crates/codegen/syntax_templates/src/typescript/cst_types.rs
- crates/codegen/syntax_templates/src/typescript/parse_output.rs
- crates/solidity/outputs/npm/crate/src/generated/cst_types.rs
- crates/solidity/outputs/npm/crate/src/generated/parse_output.rs
- crates/solidity/outputs/npm/package/generated/index.d.ts
- crates/solidity/outputs/npm/tests/src/cst-output.ts
- documentation/public/user-guide/cargo-crate/index.md
- rename `textLen()` to `textLength()` to be TypeScript idiomatic.
- hide the private `tokensThatWouldHaveAllowedMoreProgress()` API.
- fix code examples.
> update public API surface

- crates/solidity/outputs/cargo/tests/src/doc_examples/mod.rs
- crates/solidity/outputs/cargo/tests/src/doc_examples/simple_contract.rs
- crates/solidity/outputs/cargo/tests/src/doc_examples/visitor_api.rs
- crates/solidity/outputs/cargo/tests/src/lib.rs
- crates/solidity/outputs/npm/tests/src/doc-examples/simple-contract.ts
- documentation/public/user-guide/cargo-crate/index.md
- documentation/public/user-guide/npm-package/index.md
so that they never go out of sync with the API
> type check doc examples in CI

- .changeset/nice-flowers-peel.md
- crates/solidity/outputs/npm/package/index.js
- crates/solidity/outputs/npm/package/language/index.js
- crates/solidity/outputs/npm/package/syntax/index.js
- crates/solidity/outputs/npm/package/syntax/nodes/index.js
- crates/solidity/outputs/npm/package/syntax/parser/index.js
Importing slang from a native ESM module is pretty cumbersome in Node right now. Here's an example of an error you may get if you try to use a normal named import:
```
% node index.mjs
file:///private/tmp/npmproject-4/index.mjs:6
import { ProductionKind } from "@nomicfoundation/slang/syntax/parser/index.js";
^^^^^^^^^^^^^^
SyntaxError: Named export 'ProductionKind' not found. The requested module '@nomicfoundation/slang/syntax/parser/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from '@nomicfoundation/slang/syntax/parser/index.js';
const { ProductionKind } = pkg;
at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
at async …
```
> Make ESM named imports work in Node

- .changeset/nice-flowers-peel.md
- CHANGELOG.md
- crates/solidity/outputs/cargo/crate/CHANGELOG.md
- crates/solidity/outputs/npm/package/CHANGELOG.md
- scripts/changelog/CHANGELOG.md
Looks like #531 broke CI, since it used a changeset with a different package name. This absorbs the remaining changeset to unblock CI.
> absorb remaining 0.8.0 changesets

- crates/codegen/testing/src/cst_output.rs
- crates/solidity/outputs/cargo/tests/src/cst_output/generated/mod.rs
- crates/solidity/outputs/cargo/tests/src/cst_output/runner.rs
This speeds up the CST snapshot test suite and is less spammy when debugging these tests.
Locally that's from 725ms (+- 25ms) down to 650ms (+- 21ms), so not great, not terrible, but most importantly I wanted to remove the duplicated version 0.4.11 parses.
> Don't unconditionally parse twice in the CST tests

- .changeset/sharp-garlics-clean.md
Looks like one escaped validation because of the release infra broken earlier. This just updates the package name in one of them.
> fix old changesets metadata

- crates/infra/cli/generated/infra.zsh-completions
- crates/infra/cli/src/commands/run/mod.rs
This cuts down from ETA 3-5 hours down ETA ~15 minutes on the sanctuary-arbitrum dataset on Ryzen 3900X
> chore: Run smoke test suite in --release mode

- crates/codegen/parser/generator/src/parser_definition.rs
- crates/codegen/parser/generator/src/precedence_parser_definition.rs
- crates/solidity/outputs/cargo/crate/src/generated/language.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
This unindents the generated parser code and thanks to that, we succesfully re-format the `error_definition` parser code - previously it was in the raw token stream format emitted by the `quote!` macro.
> format: Ensure consistent language.rs formatting

- crates/solidity/outputs/cargo/build/src/main.rs
- crates/solidity/outputs/npm/build/src/main.rs
Changing the parser generator code obviously affects the resulting build, so make sure we re-run the build script then.
This fixes the case where modifying the code in PG does not re-run the codegen, e.g. changing the code in `quote!` macros or other logic.
> Re-run the local codegen if DSL or parser-generator changes

- .changeset/nervous-elephants-change.md
- crates/codegen/parser/generator/src/parser_definition.rs
- crates/codegen/parser/runtime/src/support/recovery.rs
- crates/solidity/outputs/cargo/crate/src/generated/language.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/recovery.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
- crates/solidity/outputs/npm/crate/src/generated/support/recovery.rs
- crates/solidity/testing/snapshots/cst_output/ContractDefinition/recovery_testbed/generated/0.4.11-failure.yml
- crates/solidity/testing/snapshots/cst_output/ContractDefinition/recovery_testbed/generated/0.5.3-failure.yml
- crates/solidity/testing/snapshots/cst_output/ContractDefinition/recovery_testbed/generated/0.7.0-failure.yml
- crates/solidity/testing/snapshots/cst_output/ContractDefinition/recovery_testbed/generated/0.8.0-failure.yml
Simpler variant of #594.
While writing an issue for the potential null parse recovery, it just hit me that we might not need to support that generally but rather just limiting that to the delimited group would give us enough bang for the buck.
TerminatedBy null parse recovery can be a bit too greedy, i.e. we might recover some unexpected item definition just because... we recovered at the final terminator. However, the delimited group is a reasonable boundary since it's simple (2-3 kinds of general delimiters versus different kinds of potentially versioned terminated statements) and the opening delimiter must always match the closing one, so it produces more reliable and self-contained recovered phrases, hence attempting to recover from a null parse in a delimited group makes more sense.
> Improve error recovery in delimited groups when can't parse anything inside

- Cargo.toml
After upgrading to Rust 1.72.0 (see #603), we now get this warning:
```log    
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
This fixes the warning by setting the resolver explicitly in `Cargo.toml`.
> use Cargo resolver v2

- Cargo.lock
- Cargo.toml
- crates/codegen/grammar/src/dsl.rs
- crates/solidity/inputs/language/Cargo.toml
Rust 1.70 includes the now-stable version in the standard library, so let's use that.
> chore: Remove now unused `once_cell` dependency

- crates/codegen/language/definition/src/compiler/analysis/definitions.rs
- crates/codegen/language/definition/src/compiler/analysis/mod.rs
- crates/codegen/language/definition/src/compiler/analysis/reachability.rs
- crates/codegen/language/definition/src/compiler/analysis/references.rs
- crates/codegen/language/definition/src/compiler/analysis/utils.rs
- crates/codegen/language/definition/src/model/types.rs
- crates/codegen/language/definition/src/utils/versions.rs
- crates/codegen/language/tests/src/fail/definitions/duplicate_expression_name/test.rs
- crates/codegen/language/tests/src/fail/definitions/duplicate_variant_name/test.rs
- crates/codegen/language/tests/src/fail/definitions/duplicate_variant_name/test.stderr
- crates/codegen/language/tests/src/fail/reachability/unused_version/test.rs
- crates/codegen/language/tests/src/fail/references/disabled_too_late/test.rs
- crates/codegen/language/tests/src/fail/references/disabled_too_late/test.stderr
- crates/codegen/language/tests/src/fail/references/enabled_too_early/test.rs
- crates/codegen/language/tests/src/fail/references/enabled_too_early/test.stderr
- crates/codegen/language/tests/src/fail/references/invalid_version/test.rs
- crates/codegen/language/tests/src/fail/references/invalid_version/test.stderr
- crates/codegen/language/tests/src/fail/references/unordered_version_pair/test.rs
- crates/codegen/language/tests/src/fail/references/unordered_version_pair/test.stderr
- crates/codegen/language/tests/src/fail/references/version_not_found/test.rs
- crates/codegen/language/tests/src/fail/references/version_not_found/test.stderr
- crates/codegen/language/tests/src/pass/tiny_language.rs
- crates/solidity/inputs/language/src/definition.rs
- crates/solidity/testing/solc/src/keywords/mod.rs
- group enabled and reserved specifiers
- remove default variants and primary expressions
- add EndOfInput to trailing_trivia
- using single references for enums to eliminate backtracking
> update language definition DSL based on feedback

- .vscode/settings.json
- crates/infra/cli/src/commands/check/mod.rs
- crates/infra/cli/src/commands/lint/mod.rs
- crates/infra/cli/src/commands/run/mod.rs
- crates/infra/cli/src/commands/setup/cargo/mod.rs
- crates/infra/cli/src/commands/test/mod.rs
- crates/infra/utils/src/cargo/workspace.rs
So that all targets/features/packages are checked in the same way.
Additionally, I'm removing `rust-analyzer.checkOnSave` from settings, as I suggest leaving this up to individual user preferences. Running checks for a large workspace is expensive.
> unify cargo check and clippy commands

- crates/solidity/inputs/language/definition/05-expressions/04-numbers/productions.yml
- crates/solidity/inputs/language/definition/05-expressions/05-strings/productions.yml
- crates/solidity/inputs/language/definition/06-yul/03-yul-expressions/productions.yml
- crates/solidity/inputs/language/src/definition.rs
- crates/solidity/inputs/language/src/dsl.rs
- crates/solidity/outputs/cargo/crate/src/generated/language.rs
- crates/solidity/outputs/cargo/tests/src/scanner/mod.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
- Moved numeric literals to use `notFollowedBy: IdentifierStart` instead of `IdentifierPart`.
- Removed `notFollowedBy: IdentifierPart` from string literals, to match the behavior of `solc`.
> fix trailing IdentifierPart in grammar

- crates/solidity/inputs/language/src/definition.rs
More details: https://github.com/NomicFoundation/slang/pull/641/files#r1384540928
> use v1 grammar for string literals

- crates/solidity/inputs/language/src/definition.rs
Split from #650 
We talked about this recently at our stand-up.
These are never reserved in the default context and are only used in the (lexical) context of pragmas, so let's reflect that in the spec.
Not updating v1 in this context since #650 is about to obsolete that and v0 does not have lexical contexts that might be impacted.
> Move pragma-specific keywords under dedicated topic

- crates/solidity/inputs/language/src/definition.rs
Part of #652 
Let's unify these definitions to be in line with what's in v0/v1 as to
not change the definition and the CST shape once we switch to using v2
as our source of truth for the parser.
This is independent whether we will want that *eventually* or not. For
now, we should keep things consistent during the migration period. After
that, we can make a decision whether we want to keep these empty nodes
in the CST or not in the absence of any separated items.
> Specify `Optional(NonEmpty(List))` in v2 where we do in v1

- crates/solidity/inputs/language/src/definition.rs
`override` is never legal there, but `internal` is legal when the contract is abstract.
Ref #652
> fix ConstructorAttribute grammar

- Cargo.lock
- Cargo.toml
- crates/solidity/testing/solc/src/keywords/mod.rs
- crates/solidity/testing/solc/src/main.rs
- crates/solidity/testing/solc/src/utils/binaries.rs
Makes sure we fetch new versions when they are released.
> download a fresh list of compiler binaries if out of date

- crates/codegen/language/definition/src/compiler/analysis/references.rs
- crates/codegen/language/definition/src/model/non_terminals/repeated.rs
- crates/codegen/language/definition/src/model/non_terminals/separated.rs
- crates/solidity/inputs/language/src/grammar.rs
It was already removed from grammar. We don't want to emit useless parents. Their references should be optional instead.
> remove `allow_empty` from DSL v2

- crates/codegen/language/definition/src/internals/parse_input_tokens/mod.rs
- crates/codegen/parser/runtime/src/support/choice_helper.rs
- crates/codegen/parser/runtime/src/support/sequence_helper.rs
- crates/codegen/spec/src/lib.rs
- crates/infra/cli/generated/infra.zsh-completions
- crates/infra/cli/src/commands/check/mod.rs
- crates/infra/cli/src/commands/lint/mod.rs
- crates/infra/utils/src/cargo/workspace.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/choice_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/sequence_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/support/choice_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/support/sequence_helper.rs
> Fix doc-links and run Rustdoc as part of the `infra check` suite

- Cargo.lock
- Cargo.toml
- crates/codegen/parser/runtime/src/kinds.rs
- crates/codegen/parser/runtime/src/napi/napi_cst.rs
- crates/codegen/parser/runtime/src/napi/napi_cursor.rs
- crates/codegen/parser/runtime/src/napi/napi_parse_error.rs
- crates/codegen/parser/runtime/src/napi/napi_parse_output.rs
- crates/codegen/parser/runtime/src/templates/kinds.rs.jinja2
- crates/codegen/parser/runtime/src/templates/language.rs.jinja2
- crates/solidity/outputs/cargo/crate/src/generated/kinds.rs
- crates/solidity/outputs/cargo/crate/src/generated/language.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/napi_cst.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/napi_cursor.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/napi_parse_error.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/napi_parse_output.rs
- crates/solidity/outputs/npm/crate/src/generated/kinds.rs
- crates/solidity/outputs/npm/crate/src/generated/language.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/napi_cst.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/napi_cursor.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/napi_parse_error.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/napi_parse_output.rs
this makes sure Rust panics are converted to JS exceptions, so that we don't crash the NodeJS process.
> add `#[napi(catch_unwind)]` everywhere

- .cargo/config.toml
- crates/codegen/parser/runtime/src/support/context.rs
- crates/codegen/parser/runtime/src/support/precedence_helper.rs
- crates/codegen/parser/runtime/src/support/scanner_macros.rs
- crates/codegen/schema/src/json_schema.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/context.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/precedence_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/support/scanner_macros.rs
- crates/solidity/outputs/npm/crate/src/generated/support/context.rs
- crates/solidity/outputs/npm/crate/src/generated/support/precedence_helper.rs
- crates/solidity/outputs/npm/crate/src/generated/support/scanner_macros.rs
Final Clippy part of #155
From the additional lint list mentioned by @OmarTawfik:
- Cargo - added everything, except the duplicate packages lint, as this is not fixable and we should strive to periodically do that ourselves. In any case, it's not something we should lint against and deny in CI
- Restriction:
- `clippy::same_name_method` - sounds useful but std traits are covered already by `should_implement_trait` and this fires on wrapper functions/traits; only 4 occurences in our codebase are intentional wrappers
- `clippy::allow_attributes_without_reason` - requires a nightly rustc feature
- `clippy::self_named_module_files` - forcing `mod.rs` onto users seems backwards, as that's one of the key issues addressed for Rust 2018 in terms of module/file path ergonomics, see …
> Add final Clippy lints

- .github/workflows/_jobs_github_pages.yml
This changes the internally used action of upload-artifact from `@main` to `@v3`. Because v4 has been recently published, which introduces quite a few performance improvements but may be in some cases incompatible with prior artifact creation workflow, we stick with the v3 that we know works.
This should fix our broken https://github.com/NomicFoundation/slang/deployments/github-pages pipeline.
Changes: https://github.com/actions/upload-pages-artifact/compare/v1.0.7...v1.0.8
Note: There was 1.0.9 published with a change that's been reverted in 1.0.10, so we might as well upgrade to 1.0.10; the only change was the back-and-forth fix (breaking change; introduced in 2.0.0) and docs change. We might upgrade to 2.0.0 but we'd need to verify if the breaking change of not running `chmod` affects …
> Bump actions/upload-pages-artifact patch ver to 1.0.8

- bin/hermit.hcl
Turns out the matching is case sensitive. This enables panic traces for `build.rs` failures:
https://github.com/rust-lang/rust/blob/920e0051cf7b80e7ea00c4fadc482e8b70f2e81b/library/std/src/sys_common/backtrace.rs#L137-L143
> fix `RUST_BACKTRACE` casing

- .vscode/settings.json
- crates/codegen/parser/generator/src/lib.rs
- crates/codegen/parser/generator/src/rust_generator.rs
- crates/codegen/parser/generator/src/typescript_generator.rs
- crates/codegen/parser/runtime/src/napi/templates/ast_selectors.rs.jinja2
- crates/codegen/parser/runtime/src/napi/templates/ast_types.ts.jinja2
- crates/solidity/outputs/cargo/build/src/main.rs
- crates/solidity/outputs/cargo/crate/src/generated/napi/napi_ast_selectors.rs
- crates/solidity/outputs/npm/build/src/main.rs
- crates/solidity/outputs/npm/crate/src/generated/napi/napi_ast_selectors.rs
- crates/solidity/outputs/npm/package/src/ast/generated/ast_types.ts
- crates/solidity/outputs/npm/tests/src/tests/ast.ts
- documentation/public/user-guide/npm-package/how-to-parse-a-file/index.md
- address later feedback on #719
- fix syntax highlighting for TS templates
- use `ReadonlyArray<T>` in return types instead of `Array<T>`.
- use `undefined` instead of `null` for optional fields, as it is more idiomatic.
> clean up AST types

- scripts/bin/infra
Rust Analyzer runs `cargo check` frequently (on every file save) on the whole workspace. This locks `$REPO_ROOT/target` directory, and prevents building/running any other `infra` commands until it is done. To avoid this during local development, let`s use a separate target directory for this binary.
Additionally, we cannot use `cargo run --bin infra_cli` directly, because `cargo run` sets a bunch of `CARGO_*` environment variables, and they get propagated to any child `cargo` commands that are spawned by `infra_cli`. We have to build and run the binary directly to ensure it has a clean env. Otherwise, they leak into things like cross-platform NAPI builds, and cause build failures.
> use separate 'target-dir' for 'infra_cli'

- .github/workflows/_jobs_ci.yml
- .github/workflows/_jobs_github_pages.yml
- .github/workflows/_jobs_publish.yml
> Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload. When selecting a SHA, you should verify it is from the action's repository and not a repository fork.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
> pin github actions ref to commit SHA

- .cspell.json
- .github/dependabot.yml
- documentation/public/internals/development.md
- add `.github/dependabot.yml` to configure dependabot for `npm`, `cargo`, `pip`, and `github-actions`.
- group `minor` and `patch` version updates in a single PR (per package manager), while leaving `major` updates to be published in separate PRs (as they might need more explicit review/testing).
- I set all updates to run once weekly (typically on Monday morning) for now. They can also be run manually from GitHub UI as needed.
closes #25
> enable dependabot updates

- crates/codegen/parser/runtime/src/parser_support/repetition_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser_support/repetition_helper.rs
- crates/solidity/outputs/cargo/tests/src/cst_output/generated/Block.rs
- crates/solidity/testing/snapshots/cst_output/Block/postfix_recovery_regression/generated/0.4.11-failure.yml
- crates/solidity/testing/snapshots/cst_output/Block/postfix_recovery_regression/generated/0.5.0-failure.yml
- crates/solidity/testing/snapshots/cst_output/Block/postfix_recovery_regression/input.sol
Fixes #788
Thanks @OmarTawfik for finding it!
I didn't think we would encounter this use case; for now, we flatten accumulated Pratt-parsed nodes and continue unwinding.
This might not be the optimal strategy, i.e. in the regression test it would be better to ignore the Skipped and rely on "skip unrecognized input" logic to handle it (this would give us correct `MemberAccessExpression` rather than `TypeName`) but we should be more consistent here and continue unwinding if we encounter the unwinding SkippedUntil ourselves; we can tweak recovery later.
> Don't panic when recovery-unwinding during Pratt-parsing

- crates/solidity/testing/sanctuary/src/datasets.rs
- crates/solidity/testing/sanctuary/src/events.rs
- crates/solidity/testing/sanctuary/src/reporting.rs
- crates/solidity/testing/sanctuary/src/tests.rs
- reset git state before running tests
- fix a bunch of nits with string/error reporting in CI
- trim null terminators from input files
> sanctuary fixes

- crates/infra/utils/src/github/mod.rs
Otherwise, this pollutes the output and we can't use the `infra` wrapper reliably to pipe the the command output like the `slang_solidity parse --json`, which would lead to malformed JSON.
> fix: Print infra command title/group to stderr

- .changeset/pink-dryers-begin.md
- crates/codegen/grammar/src/parser_definition.rs
- crates/codegen/parser/generator/src/rust_generator.rs
- crates/codegen/parser/runtime/src/cst.rs
- crates/codegen/parser/runtime/src/kinds.rs
- crates/codegen/parser/runtime/src/napi_interface/templates/ast_selectors.rs.jinja2
- crates/codegen/parser/runtime/src/parser_support/parser_result.rs
- crates/codegen/parser/runtime/src/templates/kinds.rs.jinja2
- crates/solidity/outputs/cargo/slang_solidity/src/generated/cst.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/kinds.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/napi_interface/ast_selectors.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/parser_support/parser_result.rs
- crates/solidity/testing/utils/src/node_extensions/mod.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/cst.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/kinds.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/napi_interface/ast_selectors.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/parser_support/parser_result.rs
Building block for #862 and #885
Hopefully extracting this into a smaller PR can speed up its landing, as other refactors also touch the tree shape/v1 PG etc.
> Add `TokenKind::is_trivia` and use it where appropriate

- crates/codegen/parser/runtime/src/napi_interface/cst.rs
- crates/codegen/parser/runtime/src/napi_interface/cursor.rs
- crates/codegen/parser/runtime/src/napi_interface/parse_output.rs
- crates/codegen/parser/runtime/src/napi_interface/templates/ast_selectors.rs.jinja2
- crates/solidity/outputs/cargo/slang_solidity/src/generated/napi_interface/ast_selectors.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/napi_interface/cst.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/napi_interface/cursor.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/napi_interface/parse_output.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/napi_interface/ast_selectors.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/napi_interface/cst.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/napi_interface/cursor.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/napi_interface/parse_output.rs
Rather than hand-rolling it; The codegen uses exactly the same code but with the benefit of abstracting away the unsafe details, getting rid of the only instance of `unsafe` we use.
For reference:
- `ToNapiValue`/`into_instance`: https://github.com/napi-rs/napi-rs/blob/0550c56fcf8eeec61d2e5abfa00c92a990c34e25/crates/backend/src/codegen/struct.rs#L278-L330
- `JsObject::from_raw_unchecked`/`ClassInstance::as_object`: https://github.com/napi-rs/napi-rs/blob/0550c56fcf8eeec61d2e5abfa00c92a990c34e25/crates/napi/src/bindgen_runtime/js_values/class.rs#L25
Additionally, I changed `Env` to be passed by value since it's a `Copy` newtype wrapper around pointer (no double indirection) and makes the code a bit clearer: no need to additionally dereference with `*`in the related calls, since napi-rs API …
> refactor: Use safe generated version `T::into_instance` by napi-rs

- crates/codegen/parser/runtime/src/query/engine.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/query/engine.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/query/engine.rs
- crates/testlang/outputs/cargo/tests/src/query/engine_tests.rs
Cherry-picked from https://github.com/NomicFoundation/slang/pull/884/commits/bb9238437941400b84a8b40f0d9ef953f26611f1. We need this for 0.14 to allow for more interesting queries for https://github.com/NomicFoundation/hardhat-vscode/issues/547.
> Fix nested bindings in queries

- crates/infra/cli/src/toolchains/napi/cli.rs
- crates/infra/cli/src/toolchains/napi/glibc.rs
Fixes warnings on non-GNU systems introduced with #909 
Instead of doing the conditional compilation for the remaining items that are only used for this check, the routines will be compiled in on the other systems for simplicity but only used inside a host GNU system.
The alternative is to pepper `#[cfg(target_env = "gnu")]` everywhere but IMO it'd hurt readability and we're talking about the `infra` CLI, should is only executed as part of the local development, so this should be an acceptable trade-off.
This was not caught in the CI as we only use a GNU host there, so naturally all of the code was compiled in.
Tested with `infra ci` and `infra publish npm --dry-run` on macOS and a Linux GNU.
> fixup: Silence unused warnings on non-GNU systems in glibc.rs

- .changeset/pink-bats-lie.md
- .changeset/warm-maps-give.md
- Cargo.lock
- crates/codegen/parser/runtime/Cargo.toml
- crates/codegen/parser/runtime/src/napi_interface/cst.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/napi_interface/cst.rs
- crates/solidity/outputs/cargo/slang_solidity_node_addon/Cargo.toml
- crates/solidity/outputs/npm/package/src/generated/index.d.ts
- crates/testlang/outputs/cargo/slang_testlang/src/generated/napi_interface/cst.rs
- crates/testlang/outputs/cargo/slang_testlang_node_addon/Cargo.toml
- crates/testlang/outputs/npm/package/src/generated/index.d.ts
Closes #466 
Adds the `toJSON` method to the RuleNode/TokenNode classes with the comment stating that it's unstable and for debugging purposes only. I explicitly didn't type it (it's a string) as I didn't want to publicly encode any assumptions about the shape of the data.
We can discuss further what we want to explore as part of having pure data external interface (JSON) for Slang, whether that's exporting or importing JSON, but I'd consider this a separate issue as it requires more thought and design; the original issue, from what I understand, was primarily about improving the debugging/inspection experience.
Adds hidden getter properties that is only eagerly evaluated by debugger; since it's a getter function, it shouldn't add overhead to the runtime but I have to admit, I didn't …
> Add debugging facilities to RuleNode/TokenNode exposed via N-API

- Cargo.lock
- crates/solidity/testing/sanctuary/Cargo.toml
- crates/solidity/testing/sanctuary/src/datasets.rs
Closes #892
I see that the compiler versions are already updated, e.g. https://etherscan.io/address/0ff7599a9e2c9eb63ddb42a0e8b475b579a13e08#code points to `v0.4.18+commit.9cf6e910`.
Until it propagates to the sanctuary index, let's ignore these for now to get that sweet, sweet 100% coverage.
Latest run: https://github.com/Xanewok/slang/actions/runs/8651403744
> Patch known buggy compiler versions for sanctuary

- crates/solidity/testing/sanctuary/src/tests.rs
See https://github.com/Xanewok/slang/actions/runs/8814122964 for the failing sanctuary job on the BSC dataset.
Latest run that includes this PR: https://github.com/Xanewok/slang/actions/runs/8815156720
> Ignore incompatible contracts in the BSC sanctuary

- crates/solidity/outputs/npm/tests/src/doc-examples/using-the-cursor.ts
- documentation/public/user-guide/concepts.md
Fixes some typos in the documentation.
> fix typos in user guide

- crates/infra/cli/src/commands/setup/npm/mod.rs
as `npm install --ci` doesn't fail if lock files are out of date.
> fix `npm ci` check

- crates/testlang/outputs/npm/tests/src/tests/ast.ts
- crates/testlang/outputs/npm/tests/src/tests/errors.ts
It was deprecated, showing errors during local development.
Updating with the newer alternative.
> remove toThrowError from tests

- .changeset/config.json
- .changeset/custom-changelog-generator.js
- crates/infra/cli/src/commands/publish/changesets/mod.rs
- crates/infra/cli/src/toolchains/napi/cli.rs
#957 introduced a bug in the release infra that `napi` CLI was still trying to update `optionalDependencies` not `dependencies`. This PR fixes it by adding all packages as a "fixed" set in changesets, so that they are always updated together, and thus we no longer need to run `napi prepublish`:
https://github.com/changesets/changesets/blob/main/docs/fixed-packages.md
> fix changeset publishing

- crates/codegen/language/definition/src/model/manifest.rs
- crates/codegen/runtime/cargo/src/runtime/language.rs.jinja2
- crates/codegen/runtime/generator/src/model.rs
- crates/codegen/runtime/generator/src/parser.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/generated/language.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/generated/language.rs
Part of #638 
Follow-up to #991
Pretty straightforward: instead of visiting the previously built v1 definition structure, we defer to `Language::collect_breaking_changes` as the definitions overlap - the breaking changes are defined as versions in which the syntax items may be evaluated differently, which means that these are exactly the versions that will be referenced for the conditional syntax item evaluation in the parser/lexer.
> refactor: Use collect_breaking_versions from v2 directly in PG

- Cargo.lock
- crates/codegen/ebnf/Cargo.toml
- crates/codegen/ebnf/src/builder.rs
- crates/codegen/language/definition/Cargo.toml
- crates/codegen/language/definition/src/model/manifest.rs
- crates/codegen/runtime/cargo/src/runtime/kinds.rs.jinja2
- crates/codegen/runtime/generator/Cargo.toml
- crates/codegen/runtime/generator/src/kinds.rs
- crates/codegen/runtime/generator/src/lib.rs
- crates/codegen/runtime/generator/src/model.rs
- crates/codegen/runtime/generator/src/parser/grammar/constructor.rs
Spin off of #976 
Moves the `BuiltInLabel` enum from the parser generator into the language definition and remove duplication in the `kinds` template.
> Refactor `BuiltInLabel` to avoid duplication

- Cargo.lock
- crates/codegen/language/definition/src/compiler/analysis/definitions.rs
- crates/codegen/language/definition/src/model/manifest.rs
- crates/codegen/language/tests/src/fail/definitions/duplicate_expression_name/test.rs
- crates/codegen/language/tests/src/fail/definitions/duplicate_expression_name/test.stderr
- crates/codegen/language/tests/src/fail/definitions/operator_mismatch/test.rs
- crates/codegen/language/tests/src/fail/definitions/operator_mismatch/test.stderr
- crates/codegen/runtime/cargo/src/runtime/napi_interface/ast_selectors.rs.jinja2
- crates/codegen/runtime/cargo/src/runtime/napi_interface/generated/ast_selectors.rs
- crates/codegen/runtime/generator/Cargo.toml
- crates/codegen/runtime/generator/src/ast.rs
- crates/codegen/runtime/npm/src/runtime/ast/ast_types.ts.jinja2
- crates/infra/utils/src/codegen/templates.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/napi_interface/generated/ast_selectors.rs
- crates/solidity/outputs/npm/package/src/generated/ast/generated/ast_types.ts
- crates/testlang/outputs/cargo/slang_testlang/src/generated/napi_interface/generated/ast_selectors.rs
- crates/testlang/outputs/npm/package/src/generated/ast/generated/ast_types.ts
- crates/testlang/outputs/npm/tests/src/tests/ast.ts
Uses labels to select AST nodes, which is more accurate, requires less code (instead of checking individual kinds), and also fixes a bug where additional `TerminalKind`s of `PrecedenceOperator` are not taken into account.
Closes https://github.com/NomicFoundation/slang/issues/872
Closes https://github.com/NomicFoundation/slang/issues/986
> use labels for AST selectors

- Cargo.toml
- crates/infra/cli/src/commands/publish/changesets/mod.rs
- crates/infra/utils/src/cargo/workspace.rs
Currently our publishing pipeline is failing to publish workspace crates that have internal dependencies:
https://github.com/NomicFoundation/slang/actions/runs/9468852124/job/26088399371
```log
error: all dependencies must have a version specified when publishing.
dependency `metaslang_cst` does not specify a version
```
This is a known bug/limitation of `cargo publish`: https://github.com/rust-lang/cargo/issues/11133
To get around this, I'm explicitly adding versions to all internal dependencies, and switching our versioning workflow to use `cargo set-version` to update all of them when creating the changesets PR.
> fix cargo workspace publishing

- Cargo.lock
- crates/codegen/runtime/generator/Cargo.toml
- crates/codegen/runtime/generator/src/parser/grammar.rs
- crates/codegen/runtime/generator/src/parser/grammar/constructor.rs
- crates/codegen/runtime/generator/src/parser/grammar/resolver.rs
- crates/codegen/runtime/generator/src/parser/mod.rs
Ticks the box in #638 (_Keyword trie inclusion should be reworked to not require synthetic rules over all keywords_)
This exposes the resolution step rather than treating it as an implementation detail and doesn't try to shoehorn the DSL v2 items to the old `Grammar` model as much that the PG was based on.
Moreover, this breaks up the existing grammar visitor and tries to collect or calculate more properties upfront directly from DSL v2 in order to be more explicit that they not need to depend on the collector state that tracked everything.
I didn't submit it initially because I felt I could polish it slightly further (see the `TODO` note) but since I'm focused on EDR now and this cleans up the last important box in #638 (the other one is simply reverting some rules for string literals), …
> Disentangle grammar resolution and related PG code

- crates/codegen/language/definition/src/model/terminals/trivia.rs
- crates/codegen/runtime/generator/src/parser/grammar.rs
- crates/solidity/inputs/language/src/definition.rs
Closes #638 
The trivia item from #638 is now separately tracked in #1020.
> Remove remaining mentions of #638 in the code

- .github/workflows/review-requested-slack-notification.yml
- .github/workflows/review-submitted-slack-notification.yml
As the feature is now natively supported by GitHub via real-time reminders:
- https://github.com/settings/reminders
> remove slack notification workflows

- crates/infra/cli/src/commands/test/mod.rs
- crates/solidity/outputs/npm/tests/jest.config.ts
- crates/solidity/outputs/npm/tests/package.json
- crates/testlang/outputs/npm/tests/jest.config.ts
- crates/testlang/outputs/npm/tests/package.json
- jest.config.ts
this makes failures in terminal/CI much more readable, and file names/errors contain the full paths.
> use jest projects to run tests

- .envrc
This PR adds a `.envrc` file to the root of the project, that adds `./bin/` and `./scripts/bin` to `$PATH`. If you have direnv installed this makes `hermit` work and the `infra` script accessible.
> Add .envrc to allow direnv to pick up paths

- Cargo.toml
- crates/infra/cli/src/commands/check/mod.rs
- crates/infra/cli/src/commands/test/mod.rs
- crates/infra/utils/src/cargo/workspace.rs
Makes it easier to debug failures in CI, as failures are grouped at the end, across all crates.
> use nextest for running cargo tests

- crates/infra/cli/src/commands/check/mod.rs
- crates/infra/cli/src/commands/completions/mod.rs
- crates/infra/cli/src/commands/lint/mod.rs
- crates/infra/cli/src/commands/mod.rs
- crates/infra/cli/src/commands/perf/mod.rs
- crates/infra/cli/src/commands/publish/cargo/mod.rs
- crates/infra/cli/src/commands/publish/changesets/mod.rs
- crates/infra/cli/src/commands/publish/mkdocs/mod.rs
- crates/infra/cli/src/commands/publish/npm/mod.rs
- crates/infra/cli/src/commands/run/mod.rs
- crates/infra/cli/src/commands/setup/cargo/mod.rs
- crates/infra/cli/src/commands/setup/git/mod.rs
- crates/infra/cli/src/commands/setup/mod.rs
- crates/infra/cli/src/commands/setup/npm/mod.rs
- crates/infra/cli/src/commands/test/mod.rs
- crates/infra/cli/src/commands/watch/mod.rs
- crates/infra/cli/src/toolchains/mkdocs/mod.rs
- crates/infra/cli/src/toolchains/napi/cli.rs
- crates/infra/cli/src/toolchains/napi/compiler.rs
- crates/infra/cli/src/toolchains/napi/glibc.rs
- crates/infra/cli/src/toolchains/pipenv/mod.rs
- crates/infra/utils/src/cargo/workspace.rs
- crates/infra/utils/src/commands/mod.rs
- crates/infra/utils/src/git/mod.rs
- crates/infra/utils/src/github/mod.rs
- crates/solidity/testing/sanctuary/src/datasets.rs
- crates/solidity/testing/sanctuary/src/main.rs
Release pipeline is [currently failing](https://github.com/NomicFoundation/slang/actions/runs/10281343571/job/28451407526) due to a tiny bug in `Command::run()`, where it returns a `Result<()>` even though it is panicking on error. This PR fixes that, and fixes all callsites to not expect a result.
Just a mechanical find/replace. The only functional change (the bug fix) is in `crates/infra/cli/src/toolchains/mkdocs/mod.rs` to use `Command::evaluate()` instead to check for the sub-process result.
> unblock release pipeline

- .github/workflows/benchmark.yml
- crates/infra/cli/src/commands/perf/benchmark/mod.rs
- crates/infra/cli/src/commands/perf/mod.rs
- crates/infra/cli/src/utils.rs
- allow running locally using `--dry-run`.
- limit CI runs to `main` branch only, so that we don't pollute the dashboard with merge queue runs. We can still trigger manually for other branches if needed.
> perf benchmark improvements

- crates/metaslang/bindings/src/builder/functions.rs
So that two unresolved imports don't result in the same path.
cc @ggiraldez
> use unique paths for unresolved imports in bindings

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- bin/hermit.hcl
This fixes a few issues discovered today:
- The python env bug, which bit us a few times already: #1006 a few months ago, and [more recently today](https://github.com/NomicFoundation/slang/actions/runs/10487528897/job/29049166673).
- Deduplicate CI jobs that trigger twice on PRs from branches in the main repo.
- Deduplicate `ci/ci` and `deploy/ci` jobs that cancel each other on when merging to `main` ([most recent failure](https://github.com/NomicFoundation/slang/actions/runs/10487528897/job/29048073333)).
> fix infra failures

- crates/codegen/runtime/cargo/src/runtime/wit/interface/_world.wit.jinja2
- crates/codegen/runtime/cargo/src/runtime/wit/interface/generated/_world.wit
- crates/solidity/outputs/cargo/slang_solidity/src/generated/wit/interface/generated/_world.wit
- crates/testlang/outputs/cargo/slang_testlang/src/generated/wit/interface/generated/_world.wit
It failed the [recent version update](https://github.com/NomicFoundation/slang/actions/runs/10561509832/job/29257403873). Let's remove it for now, as it is not used anywhere, and will only be consumed in a later PR under the NPM package.
> remove version tag from wit definitions

- .github/workflows/ci.yml
changesets PRs unfortunately don't queue CI checks automatically [due to GitHub limitations](https://github.com/orgs/community/discussions/57484). This leads to us having a workaround to manually close/reopen each PR before merging it, to trigger the right workflows. Which in turn, interferes with the deduplication check in the CI workflow. I'm removing it here to unblock merging #1080.
A bit wasteful, but I don't think it is worth spending more time on for now.
> fix ci queue

- crates/codegen/runtime/cargo/src/runtime/parser/lexer/mod.rs
- crates/codegen/runtime/cargo/src/runtime/parser/parser.rs.jinja2
- crates/codegen/runtime/cargo/src/runtime/parser/parser_support/choice_helper.rs
- crates/codegen/runtime/cargo/src/runtime/parser/parser_support/context.rs
- crates/codegen/runtime/cargo/src/runtime/parser/parser_support/parser_function.rs
- crates/codegen/runtime/cargo/src/runtime/parser/parser_support/recovery.rs
- crates/codegen/runtime/cargo/src/runtime/parser/scanner_macros/mod.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/parser/generated/parser.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/parser/lexer/mod.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/parser/parser_support/choice_helper.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/parser/parser_support/context.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/parser/parser_support/parser_function.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/parser/parser_support/recovery.rs
- crates/solidity/outputs/cargo/slang_solidity/src/generated/parser/scanner_macros/mod.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/parser/generated/parser.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/parser/lexer/mod.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/parser/parser_support/choice_helper.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/parser/parser_support/context.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/parser/parser_support/parser_function.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/parser/parser_support/recovery.rs
- crates/testlang/outputs/cargo/slang_testlang/src/generated/parser/scanner_macros/mod.rs
This PR contains two optimizations:
1. Replaces `TextIndex` as the position tracking structure for the parser context and instead uses the byte offset stored in a `usize`. Most of the time, the other fields computed in `TextIndex` (ie. line, column and UTF-16 offsets) are not used, and they are expensive to compute. Instead, for the very few cases where the `TextIndex` is required, this is computed for the given byte offset. This brings a 39% reduction on instructions/cycles for the parser benchmark.
```
iai::benchmarks::parser
Instructions:          2828523499|4666216487      (-39.3829%) [-1.64970x]
L1 Hits:               4140897324|6755778229      (-38.7058%) [-1.63148x]
L2 Hits:                  3784868|3630727         (+4.24546%) [+1.04245x]
RAM Hits:                   67508|67774 …
```
> Parser performance optimizations

- .changeset/two-drinks-check.md
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/ast.wit.jinja2
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/generated/ast.wit
- crates/codegen/runtime/cargo/wasm/src/runtime/wrappers/ast/mod.rs
- crates/solidity/outputs/cargo/wasm/src/generated/interface/generated/ast.wit
- crates/solidity/outputs/cargo/wasm/src/generated/wrappers/ast/mod.rs
- crates/testlang/outputs/cargo/wasm/src/generated/interface/generated/ast.wit
- crates/testlang/outputs/cargo/wasm/src/generated/wrappers/ast/mod.rs
- crates/testlang/outputs/npm/tests/src/tests/ast/ast.mts
> use `borrow<>` for AST selectors

- documentation/mkdocs.yml
- documentation/public/user-guide/rust-crate/.navigation.md
- documentation/public/user-guide/rust-crate/index.md
- documentation/public/user-guide/rust-crate/installation.md
- documentation/public/user-guide/rust-crate/using-queries.md
- documentation/public/user-guide/rust-crate/using-the-cli.md
- documentation/public/user-guide/rust-crate/using-the-cursor.md
- documentation/public/user-guide/rust-crate/using-the-parser.md
> I removed them because mkdocs will error out if they are not included in navigation.
> But looks like they introduced a new [not_in_nav](https://www.mkdocs.org/user-guide/configuration/#not_in_nav) option. I will try using it and if that works!
> That would mean they are still built/validated/served, but won't exist in the navigation sidebar.
Context: https://github.com/NomicFoundation/slang/pull/1121#discussion_r1817954065
> preserve rust user guide

- crates/metaslang/cst/src/query/engine.rs
- crates/testlang/outputs/cargo/tests/src/query/engine_tests.rs
The `OneOrMoreMatcher` would stop matching whenever it encountered a trivia item in a sequence. Since the parser may arbitrarily insert trivia items anywhere, this meant that the matched results would be incomplete.
This was found with this query from the Solidity bindings rules:
```
@specifier [InheritanceSpecifier [InheritanceTypes . @parents [_]+ .]]
```
Depending on the formatting of the parsed code, the parser would generate the children of `InheritanceTypes` with interleaved trivia items, eg. newlines if the inherited contracts/interfaces are enumerated in separate lines. Because `[_]+` would stop on the first trivia, the overall query would never match.
> Fix query engine `OneOrMoreMatcher` to skip over in-between trivia

- crates/infra/utils/src/cargo/workspace.rs
cargo prints additional stack traces for each failed fingerprint, even internal non-user-facing errors, which makes it impossible to read test failures in CI ([example](https://github.com/NomicFoundation/slang/actions/runs/11616362259/job/32349137165?pr=1138)):
```log
2024-10-31T17:03:16.0479664Z    0.346629058s  INFO prepare_target{force=false package_id=infra_utils v0.18.3 (/workspaces/slang/crates/infra/utils) target="infra_utils"}: cargo::core::compiler::fingerprint: fingerprint error for infra_utils v0.18.3 (/workspaces/slang/crates/infra/utils)/Doc { deps: false, json: false }/TargetInner { name_inferred: true, ..: lib_target("infra_utils", ["lib"], "/workspaces/slang/crates/infra/utils/src/lib.rs", Edition2021) }
2024-10-31T17:03:16.0484532Z    0.346646862s  INFO …
```
> disable cargo extra logs in CI

- .github/workflows/ci.yml
It is used to update the cache with a fresh copy, and prevent it from getting bigger over time.
> re-enable `ci` workflow on `main`

- Cargo.lock
- crates/codegen/ebnf/src/builder.rs
- crates/codegen/language/definition/src/model/manifest.rs
- crates/codegen/runtime/cargo/crate/src/runtime/cst/edge_label.rs.jinja2
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/cst.wit.jinja2
- crates/codegen/runtime/generator/src/ast/mod.rs
- crates/codegen/runtime/generator/src/kinds/mod.rs
- crates/codegen/runtime/generator/src/parser/grammar/resolver.rs
- crates/infra/cli/Cargo.toml
- crates/infra/cli/src/commands/check/mod.rs
- crates/infra/cli/src/toolchains/wasm/mod.rs
minor improvements to the codegen backend based on earlier changes in #1101 and #1120
- build npm packages in parallel
- rename `BuiltInLabel` to `PredefinedLabel` to disambiguate from the newly introduced built-ins in bindings.
- rename `wasm32-wasi` to `wasm32-wasip1`, as it is already deprecated in nightly.
> infra improvements

- crates/solidity/outputs/cargo/tests/src/bindings_output/graph/graphviz.rs
- crates/solidity/outputs/cargo/tests/src/bindings_output/runner.rs
The graph files `.mmd` and `.dot` files are not committed to the repository and hence writing them to the source directory (inside the `generated` folder) does not provide any benefit and even has some drawbacks (eg. build errors when switching branches and test are no longer present). This PR changes the output directory to be inside the `target` directory in the `solidity_cargo_tests` crate directory.
These output files are opt-in via a `RENDER_GRAPHS` environment variable. The performance impact of their generation is not too big, but they are generally unnecessary unless we're debugging binding rules.
There are also some tweaks and added information to the `.dot` file output to improve graph readability and make tracing nodes to rules easier.
> Output graph files to `target` directory and improve Graphviz output

- crates/solidity/inputs/language/bindings/rules.msgb
- crates/solidity/outputs/cargo/crate/src/generated/bindings/generated/binding_rules.rs
I found this additional required fix after merging #1159. This is so bindings can be processed for files with using directives on mapping types without crashing. We want to merge this before #1149 to get a meaningful baseline before those fixes are applied.
> Add missing `pop_begin`/`pop_end` for mapping types

- .github/workflows/sanctuary.yml
- crates/solidity/testing/sanctuary/src/events.rs
- crates/solidity/testing/sanctuary/src/main.rs
- crates/solidity/testing/sanctuary/src/results.rs
This PR adds a result output when running in CI for `sanctuary` tests, which are then passed as job outputs for each shard to the `combinedResults` job that renders them in a table. We want to use this to get a baseline and a benchmark for both correctness and performance of the bindings rules.
> Summarize Sanctuary results

- .github/workflows/sanctuary.yml
https://github.com/NomicFoundation/slang/actions/runs/12397141032
> use 32 shards for sanctuary tests

- Cargo.lock
- crates/codegen/language/definition/src/internals/parse_input_tokens/external_types.rs
- crates/codegen/language/definition/src/model/built_ins.rs
- crates/codegen/language/definition/src/model/manifest.rs
- crates/codegen/language/definition/src/model/nonterminals/enum_.rs
- crates/codegen/language/definition/src/model/nonterminals/field.rs
- crates/codegen/language/definition/src/model/nonterminals/precedence.rs
- crates/codegen/language/definition/src/model/nonterminals/repeated.rs
- crates/codegen/language/definition/src/model/nonterminals/separated.rs
- crates/codegen/language/definition/src/model/nonterminals/struct_.rs
- crates/codegen/language/definition/src/model/terminals/fragment.rs
- crates/codegen/language/definition/src/model/terminals/keyword.rs
- crates/codegen/language/definition/src/model/terminals/token.rs
- crates/codegen/language/tests/src/pass/tiny_language.rs
- crates/codegen/runtime/generator/src/bindings/mod.rs
- crates/codegen/spec/Cargo.toml
- crates/codegen/spec/src/generators/topic_page.rs
- crates/codegen/spec/src/lib.rs
- crates/solidity/outputs/spec/generated/language-definition.json
> add generated `language-definition.json`

- crates/infra/cli/src/commands/check/mod.rs
- crates/infra/cli/src/commands/lint/mod.rs
`infra check` was doing so much that isn't directly related to updating generated files. Moved to linting instead. Local REPL is much faster now.
> move lints outside `infra check`

- crates/solidity/inputs/language/bindings/rules.msgb
- crates/solidity/outputs/cargo/crate/src/generated/bindings/generated/binding_rules.rs
- crates/solidity/outputs/cargo/tests/src/bindings_output/generated/mappings.rs
- crates/solidity/testing/snapshots/bindings_output/mappings/named_parameters/generated/0.4.11-failure.txt
- crates/solidity/testing/snapshots/bindings_output/mappings/named_parameters/generated/0.8.18-success.txt
- crates/solidity/testing/snapshots/bindings_output/mappings/named_parameters/input.sol
Fixes #1213
I had to make the rule for `[MappingType]` fault-tolerant in order to accommodate for older versions of Solidity, by splitting it in two.
Questions:
- Is it possible to avoid having to make a query for each key or value parameter, and instead have `[Identifier]?` and query for its existence?
- The nodes for the parameters are "hanging in the air", as they don't participate in anything useful. Should we attach them to the mapping somehow?
> Adding definitions for mapping parameters

- .github/actions/cache/restore/action.yml
- .github/actions/cache/save/action.yml
Per this warning in CI:
> Your workflow is using a version of actions/cache that is scheduled for deprecation, actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9.
> Please update your workflow to use either v3 or v4 of actions/cache to avoid interruptions.
> Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
cc @beta-ziliani
> upgrade `actions/cache` to v4.2.0

- crates/metaslang/bindings/src/builder/loader/mod.rs
- crates/metaslang/bindings/src/builder/mod.rs
- crates/metaslang/bindings/src/graph/definition.rs
- crates/metaslang/bindings/src/graph/mod.rs
- crates/metaslang/bindings/src/graph/reference.rs
- crates/metaslang/bindings/src/graph/resolver.rs
This hopefully reduces resolution time when not all references (eg. those in dependencies) need to be resolved, but requires the `BindingGraph` to retain both the `StackGraph` and the `Resolver` (with the database of partial path candidates and the partial paths arena).
This PR also includes an optimization to the resolution algorithm. When selecting candidates to extend an already complete partial path, discard those that would immediately push a `@typeof` symbol (eg. through the path that replaces a variable by its type) since we know those will never resolve. This can halve the number of evaluated partial paths (ie. references that resolve to a variable/field definition) and provide a very significant performance gain in some cases.
> Resolve references lazily

- .changeset/famous-monkeys-move.md
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/bindings.wit.jinja2
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/generated/bindings.wit
- crates/codegen/runtime/cargo/wasm/src/runtime/wrappers/bindings/mod.rs
- crates/codegen/runtime/npm/package/wasm/generated/interfaces/nomic-foundation-slang-bindings.d.ts
- crates/metaslang/bindings/generated/public_api.txt
- crates/metaslang/bindings/src/graph/definition.rs
- crates/metaslang/bindings/src/graph/mod.rs
- crates/metaslang/bindings/src/graph/resolver.rs
- crates/solidity/outputs/cargo/tests/src/binding_resolver.rs
- crates/solidity/outputs/cargo/tests/src/lib.rs
- crates/solidity/outputs/cargo/wasm/src/generated/interface/generated/bindings.wit
- crates/solidity/outputs/cargo/wasm/src/generated/wrappers/bindings/mod.rs
- crates/solidity/outputs/npm/package/wasm/generated/interfaces/nomic-foundation-slang-bindings.d.ts
- crates/solidity/outputs/npm/tests/src/compilation/binding-graph.test.mts
- crates/testlang/outputs/cargo/wasm/src/generated/interface/generated/bindings.wit
- crates/testlang/outputs/cargo/wasm/src/generated/wrappers/bindings/mod.rs
- crates/testlang/outputs/npm/package/wasm/generated/interfaces/nomic-foundation-slang-bindings.d.ts
Closes #1216
Implements `Definition::references()` in bindings API by eagerly resolving all remaining unresolved references and then building a reverse mapping from definitions to references.
> Implement `Definition::references()`

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/actions/cache/save/action.yml
- .github/actions/devcontainer/run/action.yml
- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/sanctuary.yml
- .gitmodules
- crates/infra/cli/src/commands/perf/benchmark/mod.rs
- crates/infra/utils/src/github/mod.rs
We cannot run the full CI in devcontainers, as we will run out of disk space in GitHub Actions. Instead, we just validate the devcontainer is built correctly by running a minimal smoke test in a single `devcontainer` workflow, and move hte other workflows to run on the bare GitHub Actions image.
Changes cherry-picked from #1225
> move workflows outside devcontainer

- crates/codegen/runtime/cargo/crate/src/runtime/parser/lexer/mod.rs
- crates/codegen/runtime/cargo/crate/src/runtime/parser/parser.rs.jinja2
- crates/codegen/runtime/cargo/crate/src/runtime/parser/parser_support/context.rs
- crates/codegen/runtime/cargo/crate/src/runtime/parser/parser_support/parser_function.rs
- crates/codegen/runtime/cargo/crate/src/runtime/parser/parser_support/recovery.rs
- crates/codegen/runtime/cargo/crate/src/runtime/parser/parser_support/separated_helper.rs
- crates/codegen/runtime/cargo/crate/src/runtime/parser/scanner_macros/mod.rs
- crates/codegen/runtime/generator/src/parser/codegen/keyword_scanner_definition.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser/generated/parser.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser/lexer/mod.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser/parser_support/context.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser/parser_support/parser_function.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser/parser_support/recovery.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser/parser_support/separated_helper.rs
- crates/solidity/outputs/cargo/crate/src/generated/parser/scanner_macros/mod.rs
- crates/testlang/outputs/cargo/crate/src/generated/parser/lexer/mod.rs
- crates/testlang/outputs/cargo/crate/src/generated/parser/parser_support/context.rs
- crates/testlang/outputs/cargo/crate/src/generated/parser/parser_support/parser_function.rs
- crates/testlang/outputs/cargo/crate/src/generated/parser/parser_support/recovery.rs
- crates/testlang/outputs/cargo/crate/src/generated/parser/parser_support/separated_helper.rs
- crates/testlang/outputs/cargo/crate/src/generated/parser/scanner_macros/mod.rs
Found while cleaning up the remaining `TODO` comments before the release (see #1251).
Fixed This one since it was a minor change to stop allocating strings on every scanner invocation.
Closes #1001
> reduce scanner string allocations

- crates/metaslang/cst/src/nodes.rs
- crates/metaslang/graph_builder/src/variables.rs
This PR fixes spelling mistakes in code comments:
- Corrects "reproducable" to "reproducible" in node identifier comments
- Corrects "enviroment" to "environment" in variable-related comments
These changes only affect comments and do not modify any functional code.
> Fix typos in comments

- .github/workflows/ci.yml
Observed that CI is no longer running on changeset PRs (example #1270). Not sure why yet. But let's remove the deduplication condition for now to unblock the release, and I will follow up with a fix sometime later.
> remove deduplication condition from `ci.yml`

- .cspell.json
- documentation/public/user-guide/.navigation.md
- documentation/public/user-guide/07-semantic-analysis/03-solidity-builtins/examples/01-solidity-builtins.test.mts
- documentation/public/user-guide/08-examples/.navigation.md
- documentation/public/user-guide/08-examples/01-list-functions-in-contract/examples/list-functions-in-contract.mts
- documentation/public/user-guide/08-examples/01-list-functions-in-contract/examples/test-list-functions.test.mts
- documentation/public/user-guide/08-examples/01-list-functions-in-contract/index.md
- documentation/public/user-guide/08-examples/02-find-usages/examples/find-usages.mts
- documentation/public/user-guide/08-examples/02-find-usages/examples/test-find-usages.test.mts
- documentation/public/user-guide/08-examples/02-find-usages/index.md
- documentation/public/user-guide/08-examples/03-jump-to-definition/examples/jump-to-definition.mts
- documentation/public/user-guide/08-examples/03-jump-to-definition/examples/test-jump-to-definition.test.mts
- documentation/public/user-guide/08-examples/03-jump-to-definition/index.md
- documentation/public/user-guide/08-examples/common/compilation-builder.mts
- documentation/public/user-guide/08-examples/common/find-terminal-node-at.mts
- documentation/public/user-guide/08-examples/common/sample-contract.mts
- documentation/public/user-guide/08-examples/common/sample-contract.sol
- documentation/public/user-guide/08-examples/index.md
- documentation/public/user-guide/index.md
Resubmitting this since #1267 was closed when #1257 was merged.
Adds a section with standalone examples to the user guide. These examples demonstrate almost all the Slang APIs.
> Add standalone examples to the user guides

- documentation/public/user-guide/03-concepts/index.md
- documentation/public/user-guide/05-syntax-trees/01-parsing-source-code/index.md
- documentation/public/user-guide/05-syntax-trees/03-navigating-with-cursors/index.md
- documentation/public/user-guide/05-syntax-trees/04-using-ast-types/index.md
- documentation/public/user-guide/06-query-language/01-query-syntax/index.md
- documentation/public/user-guide/06-query-language/02-executing-queries/index.md
- documentation/public/user-guide/07-semantic-analysis/02-binding-graph/index.md
- documentation/public/user-guide/08-examples/01-list-functions-in-contract/index.md
- documentation/public/user-guide/08-examples/02-find-usages/index.md
- documentation/public/user-guide/08-examples/03-jump-to-definition/index.md
- apply remaining suggestions from #1257
- add grammar links to any remaining node names in user guides
- change query hilighting language to `smalltalk` as it is more readable
> documentation fixes

- crates/codegen/language/definition/src/model/nonterminals/precedence.rs
- crates/codegen/language/definition/src/model/nonterminals/struct_.rs
- crates/solidity/outputs/spec/generated/language-definition.json
This commit adds a serde annotation to the two `IndexMap` fields in the language model to make them use a sequence representation rather than an object representation - this ensures that when emitting json, the ordering of the fields is correctly represented.
> Preserve field ordering in `language-definition.json`

- .changeset/wicked-dingos-drop.md
- .cspell.json
- crates/solidity/inputs/language/src/definition.rs
- crates/solidity/outputs/cargo/crate/src/generated/extensions/built_ins.rs
- crates/solidity/outputs/spec/generated/language-definition.json
- crates/solidity/testing/snapshots/bindings_output/yul/all_built_ins/generated/0.4.11-failure.txt
- crates/solidity/testing/snapshots/bindings_output/yul/all_built_ins/generated/0.4.14-failure.txt
- crates/solidity/testing/snapshots/bindings_output/yul/all_built_ins/generated/0.5.0-failure.txt
- crates/solidity/testing/snapshots/bindings_output/yul/all_built_ins/generated/0.8.18-failure.txt
- crates/solidity/testing/snapshots/bindings_output/yul/all_built_ins/generated/0.8.27-success.txt
- crates/solidity/testing/snapshots/bindings_output/yul/all_built_ins/generated/0.8.8-failure.txt
- crates/solidity/testing/snapshots/bindings_output/yul/all_built_ins/input.sol
These two yul builtins are missing from the language definition:
1. `codesize()`
2. `codecopy(t, f, s)`
> Add `codesize` and `codecopy` yul builtins

- crates/codegen/runtime/cargo/crate/src/extensions/bindings/mod.rs
- crates/codegen/runtime/cargo/crate/src/runtime/bindings/mod.rs
- crates/codegen/runtime/cargo/crate/src/runtime/compilation/unit.rs
- crates/solidity/outputs/cargo/crate/generated/public_api.txt
- crates/solidity/outputs/cargo/crate/src/extensions/bindings/mod.rs
- crates/solidity/outputs/cargo/crate/src/generated/bindings/mod.rs
- crates/solidity/outputs/cargo/crate/src/generated/compilation/unit.rs
- crates/solidity/outputs/cargo/tests/src/binding_resolver.rs
- crates/solidity/outputs/cargo/tests/src/bindings_output/runner.rs
- crates/solidity/testing/perf/src/tests/bindings_build.rs
- crates/solidity/testing/sanctuary/src/tests.rs
- crates/testlang/outputs/cargo/crate/src/extensions/bindings/mod.rs
- crates/testlang/outputs/cargo/crate/src/generated/bindings/mod.rs
- crates/testlang/outputs/cargo/crate/src/generated/compilation/unit.rs
Returning a `Result` was previously required because adding built-ins to the initial empty binding graph was done by parsing a generated Solidity source file and processing it normally. But now the partial graph to support built-ins is being generated directly.
> Remove error variant when creating a `BindingGraphBuilder`

- crates/solidity/testing/sourcify/src/command.rs
- crates/solidity/testing/sourcify/src/compilation_builder.rs
- crates/solidity/testing/sourcify/src/run.rs
When building the `CompilationUnit` for Sourcify tests we were missing the registration of the resolved imports. This information is later used by the binding graph to link the partial graphs from each file. Without this, resolving symbols in imported files didn't work properly.
This PR also includes two additional improvements:
- the argument to `--shard-count` is validated and can now accept the value 256 (it wouldn't previously because it was stored in a `u8`)
- when reporting failures, always print the contract name alongside the version (this makes it easier to iterate on failing contracts using the `--contract` option)
> Register resolved imports when building the `CompilationUnit` on Sourcify tests

- crates/infra/cli/src/commands/publish/changesets/mod.rs
- crates/infra/cli/src/commands/setup/git/mod.rs
The repo-wide config causes issues in other workflows when debugging CI failures.
> use localized `git config` calls

- llms.txt
Adds a brief `llms.txt` to the website root directory.
See https://llmstxt.org/ for more information.
> create `llms.txt` for user guide

- crates/codegen/runtime/cargo/crate/src/ir/builder.rs.jinja2
- crates/codegen/runtime/cargo/crate/src/ir/nodes.rs.jinja2
- crates/codegen/runtime/cargo/crate/src/runtime/cst/nonterminal_kind.rs.jinja2
- crates/codegen/runtime/cargo/crate/src/runtime/cst/terminal_kind.rs.jinja2
- crates/codegen/runtime/cargo/wasm/src/runtime/interface/cst.wit.jinja2
- crates/codegen/runtime/generator/src/parser/codegen/precedence_parser_definition.rs
Context: https://github.com/NomicFoundation/slang/pull/1388/files/d3dae389c231441b4ba9a684b4be3b7c5dca73fd#r2248599409
> Looks like a few places in the codebase were converting already PascalCase identifiers, which will override the capitalization in the grammar like this. Luckily, fixing it doesn't break existing source code, so we can just do it. I submitted #1403 with the fixes.
> fix double-casing pascal identifiers

- .github/workflows/publish.yml
- README.md
- crates/infra/cli/src/commands/publish/cargo/mod.rs
- crates/metaslang/bindings/Cargo.toml
- crates/metaslang/cst/Cargo.toml
- crates/metaslang/graph_builder/Cargo.toml
- crates/solidity/outputs/cargo/cli/Cargo.toml
- crates/solidity/outputs/cargo/cli/README.md
- crates/solidity/outputs/cargo/crate/Cargo.toml
- crates/solidity/outputs/cargo/crate/README.md
- crates/solidity/outputs/npm/package/README.md
This will still not execute until we merge the most recent `Bump Version` PR.
> re-enable publishing to crates.io
